### ISSUE TITLE
Konzeptaufgabe: Git Remote

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#103]
Idee:
Die Studies können hier schon ihr Remote Repo für das Dungeon vorbereiten.

**Comment by cagix** [comment]
@AMatutat Diese Aufgabe wird auch noch für das erste Blatt benötigt.

**Comment by AMatutat** [comment]
@cagix Brauchen wir da was explizites? Eigentlich üben die das automatisch sobald sie im Dungeon unterwegs sind.

**Comment by cagix** [comment]
> @cagix Brauchen wir da was explizites? Eigentlich üben die das automatisch sobald sie im Dungeon unterwegs sind.

Den Dungeon geben sie aber erst in der zweiten Woche ab und die Abgabe der Konzeptübung in Woche 2 ist ja ein paar Tage früher. Es könnte alles klappen, aber wenn nicht, dann haben wir kaum noch Möglichkeiten, irgendwie hilfreich einzugreifen (zeitlich). 

Ich dachte, wenn die das auf dem ersten Konzeptblatt machen müssen, dann haben wir (a) die Daten und (b) wissen wir, ob es geklappt hat und haben dann nochmal ne ganze Woche Zeit, ggf. Support zu leisten ...

**Comment by cagix** [comment]
> > @cagix Brauchen wir da was explizites? Eigentlich üben die das automatisch sobald sie im Dungeon unterwegs sind.
> 
> Den Dungeon geben sie aber erst in der zweiten Woche ab und die Abgabe der Konzeptübung in Woche 2 ist ja ein paar Tage früher. Es könnte alles klappen, aber wenn nicht, dann haben wir kaum noch Möglichkeiten, irgendwie hilfreich einzugreifen (zeitlich).
> 
> Ich dachte, wenn die das auf dem ersten Konzeptblatt machen müssen, dann haben wir (a) die Daten und (b) wissen wir, ob es geklappt hat und haben dann nochmal ne ganze Woche Zeit, ggf. Support zu leisten ...

OK, ich bin (a) zu früh auf gestanden und (b) eigentlich in der Prüfung :)

Du hast Recht. Die Remote-Aufgabe ist einfach die letzte Aufgabe, wo sie ihr Repo anlegen und das Vorgaberepo als Remote eintragen und pullen/pushen. Das sollte reichen, der Rest kommt dann mit dem Dungeon.

**Comment by AMatutat** [comment]
Schließ ab
