### ISSUE TITLE
Konzeptaufgabe: Observer-Pattern

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#106]
Aufgabe:
Ein Großhandel erhält regelmäßig unterschiedliche und neue Ware und informiert seine Kunden, sofern diese sich registriert haben, darüber. Kunden können sich auch abmelden. Registrierte Kunden prüfen, ob sie noch genug Ware des Typen im Lager haben, falls nicht, bestellen diese Ware beim Großhandel. 
Implementieren Sie das Verhalten mithilfe des Observer-Patterns. 

Vorgabe: 
- Enum `WarenTyp` mit ein paar Waren
- `Großhandel`-Klasse 
  -  HashMap `Lager` mit WarenTyp und Anzahl   
  -  `public void bestellungsEingang(Einzelhandel kunde, WarenTyp ware, int anzahl) `      
      - Prüft ob noch genug im Lager ist
              - ja:`kunde.liefern` 
              - nein: do nothing   
  - Irgendeinen Loop der Ware "erstellt" damit der Großhandel den Einzelhandel informieren kann
- `Einzelhandel`-Klasse
   - HashMap `Lager` mit WarenTyp und Anzahl   
   - Kennt seinen Großhandel  
   - `private void bestellen(WarenTyp ware , int anzahl)`: Bestellt die Ware beim Großhändler. 
   - `public void liefern(WarenTyp ware, int anzahl)`: fügt Ware dem Lager hinzu.

**Comment by AMatutat** [comment]
@cagix passt das?

**Comment by cagix** [comment]
> @cagix passt das?

Die Idee geht in die richtige Richtung. 

- Mir ist noch nicht so richtig klar, wie das Bestellen und Liefern in das Observer-Pattern passt?
- Die Methode `bestell` ist beim Großhandel angesiedelt, klingt vom Namen her für mich aber eher nach einer Methode beim Kunden. Die inhaltliche Skizze deutet aber auf Großhandel hin, aber dann würde ich die Methode irgendwie umbenennen: „bestelleingang()“ oder so?
- `liefern` würde für mich definitiv im Großhandel angesiedelt sein (der liefert mir was), aber da macht die inhaltliche Skizze nicht so richtig Sinn, oder?

**Comment by AMatutat** [comment]
> Mir ist noch nicht so richtig klar, wie das Bestellen und Liefern in das Observer-Pattern passt?

Das Szenario ist absolut Käse, aber darum geht es ja nicht (unbedingt). Der Rahmen ist dafür schön schlank und die Aufgabe kann sich auf das Observerpattern konzentrieren, nicht auf anderen kram. 

Was die Methoden angeht, haste recht. Da habe ich irgendwie Unfug gemacht. Hab es mal gefixt.

**Comment by cagix** [comment]
> > Mir ist noch nicht so richtig klar, wie das Bestellen und Liefern in das Observer-Pattern passt?
> 
> Das Szenario ist absolut Käse, aber darum geht es ja nicht (unbedingt). Der Rahmen ist dafür schön schlank und die Aufgabe kann sich auf das Observer-Pattern konzentrieren, nicht auf anderen kram.

och, das szenario finde ich eigentlich super. das passt doch toll zum pattern.

**Comment by AMatutat** [comment]
@cagix 

Ich habe grade mal versucht ein mwe zu basteln und meine IDE weißt mich darauf hin, dass `Observer` und `Observerable` deprecated sind.
Wie machst du das in der Vorlesung?

**Comment by cagix** [comment]
> @cagix
> 
> Ich habe grade mal versucht ein mwe zu basteln und meine IDE weißt mich darauf hin, dass `Observer` und `Observerable` deprecated sind. Wie machst du das in der Vorlesung?

keine ahnung, das weiss ich noch nicht. die beiden interfaces stammen afaik aus dem swing-dunstkreis, kann also gut sein, dass da mal was verschütt geht. 

ich würde vermutlich hingehen, und mir ein eigenes interface basteln. etwa so wie in https://en.wikipedia.org/wiki/Observer_pattern#UML_class_diagram ...

**Comment by AMatutat** [comment]
klingt nach dem way to go

**Comment by cagix** [comment]
der weg des kehrers.

**Comment by AHeinisch** [comment]
Ich könnte mir vorstellen, hierfür die Lösung zu entwickeln. 
@AMatutat Willst du hier noch was ändern?

**Comment by AMatutat** [comment]
> Ich könnte mir vorstellen, hierfür die Lösung zu entwickeln.
@AMatutat Willst du hier noch was ändern?

@AHeinisch Kannste machen.
