### ISSUE TITLE
Konzeptaufgabe: Logging

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#109]
Idee:
Code vorgeben und die Studies müssen dann an bestimmten stellen Logging einbauen. Kann man super mit dem Debuger kombinieren. Wo ist denn die stelle X,Y,Z.

**Comment by AHeinisch** [comment]
Kann man hier nicht eine Liste befüllen und es gibt eine Bedingung in der Vorgabe welche bestimmt ob es eingetragen wird. Per Logging Level könnte dann zusätzlich jeder schritt geloggt werden. Falls dies etwas sein könnte was ihr euch vorgestellt habt könnt ihr mich zuweisen dann arbeite ich das weiter aus. @AMatutat

**Comment by cagix** [comment]
@AHeinisch Im Prinzip könnte das in die Richtung gehen. Ich fände es schön, wenn der Code noch etwas komplexer werden würde und man tatsächlich (a) die verschiedenen Log-Level mal nutzen muss (also Info und Warning oder so) und (b) wenn man verschiedene Logger hätte (zwei verschiedene Klassen plus den Root-Logger) und (c) wenn man die Ausgabe unterschiedlich formatieren müsste (einer der Logger könnte zwei Handler bekommen, wobei der eine alles einfach formatiert auf der Konsole ausgibt und der andere Handler nur die Warnings und höher in eine Text-Datei schreibt).

Zuweisen kannst Du Dich doch auch selbst?

**Comment by AHeinisch** [comment]
Zuweisen kann ich mich nicht war mir aber auch nicht sicher ob das was ich mir vorgestellt habe ausreichen würde.

**Comment by cagix** [comment]
schräg. aber ich habe dich dann mal assigned.

siehe meinen letzten kommentar, du bist auf dem richtigen weg :)

**Comment by cagix** [comment]
@AHeinisch Was ist hier der Stand? Wir brauchen die Aufgabe nächste Woche.

**Comment by AHeinisch** [comment]
Also Logging liegt theoretisch fertig in Entwicklung, muss nur aufgesplittet werden, vielleicht kann das ja @jedi101 machen.

**Comment by AHeinisch** [comment]
Ja, es befindet sich dort bereits im Master.

**Comment by cagix** [comment]
> Also Logging liegt theoretisch fertig in Entwicklung, muss nur aufgesplittet werden, vielleicht kann das ja @jedi101 machen.

hmmm, damit geht aber dann die info über den ersteller verloren (die "kleinen Spielrepos" werden bald wieder abgeräumt). besser wäre es vermutlich, wenn du das selbst splitten und in die haupt-repos einreichen würdest.

**Comment by jedi101** [comment]
>  ...damit geht aber dann die info über den ersteller verloren...

@cagix stimmt auch wieder. @AHeinisch - Dann splitte Du das lieber und reichst das im Hauptrepo ein. Ich ruder dann mal zur nächsten Aufgabe.

**Comment by cagix** [comment]
@AHeinisch Bitte auch immer den PR verlinken ... Sonst frage ich irgendwann wieder nach, was wohl damit ist ;)

Hier kann zu, oder?
