### ISSUE TITLE
Konzeptaufgabe: JUnit Basic

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#110]
Neue Aufgabe: 

Testen Sie die `add`- und `remove`-Methode einer `ArrayList` mit JUnit (4.x oder 5.x).

Erstellen Sie im Paket `test` eine Testklasse `ArrayListTest` mit dem Attribut `private ArrayList<String> list;`. `list` ist dabei Ihre zu testende Klasse.

Deklarieren Sie die Methoden `setUp` und `tearDown`. Initialisieren Sie `list` innerhalb von von `setUp` und fügen Sie zwei Elemente (`"1"` und `"2"`) hinzu. Stellen Sie mit `assume...` als Vorbedingung sicher, dass `list` genau zwei Elemente enthält.

Deklarieren Sie nun die Testmethoden `test_add` und `test_remove`. Testen Sie innerhalb dieser Testmethoden, ob ein Element korrekt eingefügt wird und korrekt entfernt wird. Überprüfen Sie dafür den Rückgabewert von `add` und `remove` sowie die Zustände von `list` vor und nach dem Einfügen bzw. Entfernen.

*Hinweis:* Verwenden Sie innerhalb der Testmethoden nicht die `assume...`-Methoden, weil diese lediglich einen Vorbedingungstest darstellen. Verwenden sie stattdessen `assert...`.

**Comment by Tobias321** [comment]
Führen Sie mit JUnit (4.x oder 5.x) einen White-Box-Test durch. Testen Sie die Methoden `a`, `b`, `c`, `d` und `e`.

Überlegen Sie sich, für welche Testfälle welche Methoden gleiche Ergebnisse liefern könnten und für welche Testfälle ungleiche Ergebnisse geliefert werden könnten. Führen Sie dafür eine Äquivalenzklassenanalyse durch und erstellen Sie daraus Testfälle. Führen Sie zusätzlich eine Grenzwertanalyse durch und ergänzen Sie die Testfälle. Dokumentieren Sie die Ergebnisse der Äquivalenzklassen- und Grenzwertanalyse nachvollziehbar.

Überlegen Sie sich für jede Methode eine Beschreibung, die angibt, was die jeweilige Methode berechnet.

Überlegen Sie, welche Methoden richtige oder falsche Ergebnisse anhand Ihrer Beschreibung liefert.

Hält jede Methode für alle Werte in praktisch annehmbarer Zeit an?

```java
public class WhiteBoxTest {
    public long a(int x) {
        return ((x + 1L) * x) / 2L;
    }

    public long b(int x) {
        long s = 0;
        for (int i = 1; i <= x; i++) {
            s += i;
        }
        return s;
    }

    public int c(long x) {
        int c = 2;
        for (long i = 2; i <= x / 2; i++) {
            if (x % i == 0) {
                c++;
            }
        }
        return c;
    }

    public int d(long x) {
        int c = 0;
        for (long i = 1; i <= x; i++) {
            if (x % i == 0) {
                c++;
            }
        }
        return c;
    }

    public int e(int x) {
        int c = 1;
        for (int i = 1; i <= x / 2; i++) {
            if (x % i == 0) {
                c++;
            }
        }
        return c;
    }

}
```

**Comment by cagix** [comment]
Wenn ich das richtig lese, ersetzt Du den Aufgabentext (Beschreibung des Verhaltens des Zinssatzes in Bezug auf das Alter) durch konkreten Code. Dazu soll eine ÄK/GW-Analyse gemacht werden und der Spass implementiert werden.

- Die Konzeptaufgaben sollen etwas kleiner werden, da sie zusätzlich zu den Dungeon-Aufgaben bearbeitet werden müssen. D.h. ich würde die ÄK/GW-Analyse und die Implementierung der TF trennen (zwei verschiedene Konzeptaufgaben, wobei ich für die Implementierung die ÄK/GW vorgeben würde -- Folgefehler!).
- 
- Ich finde eine textuelle Beschreibung einfacher zu verstehen als halbwegs "kryptischen" Code, der ja erstmal analysiert und verstanden werden muss, bevor man überhaupt Richtung ÄK/GW denken kann. Baust Du damit nicht noch eine zusätzliche Hürde ein?

**Comment by Tobias321** [comment]
@cagix Das siehst du richtig. Es war eher mehr eine Idee. Die Implementierung würde vorgegeben werden. Aber das wäre eine zusätzliche Hürde und würde sich eigentlich auch weiter weg von dem eigentlichen Thema der Konzeptaufgabe bewegen...

Könnte man zu einem Blackbox-Test eine ÄK/GW-Analyse machen?

**Comment by cagix** [comment]
> @cagix Das siehst du richtig. Es war eher mehr eine Idee. Die Implementierung würde vorgegeben werden. Aber das wäre eine zusätzliche Hürde und würde sich eigentlich auch weiter weg von dem eigentlichen Thema der Konzeptaufgabe bewegen...

ich meine, evtl. könnte man das als zusätzliche konzeptaufgabe mit mehr punkten anbieten. 

die studis sollen ja frei wählen aus den pools und ein pool wären die konzeptaufgaben. andererseits wollten wir für die konzeptaufgaben feste abgabedatumse einbauen. 

vielleicht könnte man das so organisieren, dass es für ein abgabedatum u.u. mehrere verschiedene varianten einer konzeptaufgabe gibt und die studis sollen sich davon dann eine auswählen. 

@AMatutat any thoughts?

> 
> Könnte man zu einem Blackbox-Test eine ÄK/GW-Analyse machen?

ja schon, aber man bräuchte auf alle fälle eine art beschreibung, was der code macht in abhängigkeit von den parametern.

**Comment by AMatutat** [comment]
> vielleicht könnte man das so organisieren, dass es für ein abgabedatum u.u. mehrere verschiedene varianten einer konzeptaufgabe gibt und die studis sollen sich davon dann eine auswählen.

klingt interessant (und aufwendig) 


Zu Tobis Idee:
Ich find den Vorschlag als eine Aufgabe Code zu geben für den dann Tests geschrieben bzw. eine Analyse durchgeführt werden muss, gar nicht so schlecht. Ist auch gar nicht so realitätsfern. Der Code sollte aber weniger Kryptisch sein. 
Evtl. reicht dann auch eine Aufgabe für JUnit. Also #110 und #111 zusammen.

**Comment by cagix** [comment]
> > vielleicht könnte man das so organisieren, dass es für ein abgabedatum u.u. mehrere verschiedene varianten einer konzeptaufgabe gibt und die studis sollen sich davon dann eine auswählen.
> 
> klingt interessant (und aufwendig)

hmmm, aufwändig wird das für die tutoren, die ggf. verschiedene aufgaben korrigieren müssen. aber wenn in der junit-woche mehrere unterschiedlich schwere junit-aufgaben zur verfügung stehen und jeder nur eine machen/abgeben darf? man müsste nur die aufgaben entsprechend markieren ...

**Comment by cagix** [comment]
> Zu Tobis Idee: Ich find den Vorschlag als eine Aufgabe Code zu geben für den dann Tests geschrieben bzw. eine Analyse durchgeführt werden muss, gar nicht so schlecht. Ist auch gar nicht so realitätsfern. Der Code sollte aber weniger Kryptisch sein. Evtl. reicht dann auch eine Aufgabe für JUnit. Also #110 und #111 zusammen.

Ja, Code finde ich auch gut, aber das muss dann übersichtlich(er) sein. Auf die Diskussionen, dass irgendwer irgendwas übersehen hat, weil zu komplex, habe ich eigentlich keine Lust ;)

**Comment by Tobias321** [comment]
Vielleicht ist es auch keine gute Idee, eine Implementierung vorzugeben, und die bisherige Aufgabe ist bereits gut. Ich bin so schrecklich unkreativ. :(

Andernfalls muss auf jeden Fall der Code überarbeitet werden (`int`-Parameter verwenden), spezifiziert werden durch Java-Docs und die Aufgaben angepasst werden (-hält in praktisch annehmbarer Zeit an, +welche Methoden sind gemäß der Spezifikation richtig oder falsch...), und es sollte ein Blackbox-Test gemacht werden, wobei wir zwar den Code vorgeben, aber dieser _nicht_ "verstanden" werden muss, sondern durch die Testfälle geprüft werden soll.

**Comment by cagix** [comment]
> Ich bin so schrecklich unkreativ. :(

#hierauch

**Comment by Tobias321** [comment]
Geht der Code so?

**Comment by cagix** [comment]
also, zwei dinge: 

(a) ich finde die idee immer noch gut.

(b) der code ist immer noch recht komplex. es werden fremde dinge mit reingemischt, was einerseits gut ist, die konzeptaufgabe andererseits aber auch wieder schwieriger macht.

ich denke, die kommentare erklären ungefähr, was der code inhaltlich machen soll. mir ist die zielsetzung aber nicht klar: die kommentare deuten darauf hin, dass `x in [-1k, +1k]` ist. der code selbst prüft aber nur auf `x > 1k`. d.h. soll der kommentar erklären, was der code macht (damit die studis daraufhin die äk/gw-analyse machen und die tf implementieren) oder sollen die studis auch darüber hinaus inhaltliche fehler finden?

**Comment by cagix** [comment]
@AMatutat @Tobias321 Stimmt eigentlich die Zuordnung der alten Aufgabe zum Thema überhaupt? Im ersten JUnit-Teil ("Basics") erzähle ich den Leuten, wie man Tests technisch mit JUnit umsetzt, also `@Test` und so. Und erst im zweiten Teil erzähle ich was über ÄK/GW/... 

D.h. konsequenterweise müsste hier eigentlich Code mit zwei..drei Methoden und eine Handvoll von Testfällen vorgegeben werden, die die Studis dann in/mit JUnit umsetzen und dabei Dinge wie `@Test`, `@before`, `@beforeClass`, erwartete Exceptions, Testsuiten, ... mal umsetzen.

Die Testfälle wären dann als kurzer Text (was ist die Idee) plus die In- und Output-Werte vorgegeben.

**Comment by AMatutat** [comment]
>  Stimmt eigentlich die Zuordnung der alten Aufgabe zum Thema überhaupt?

Ich gehe mal davon aus, früher wurde das alles auf einen Schlag zusammen gemacht. Daher gabs evtl. gar keine richtig "basic" Aufgaben.

**Comment by cagix** [comment]
hmmm, siehe https://github.com/PM-Dungeon/PM-Lecture/issues/110#issuecomment-1047808011 ... hier nur was zum üben der technik, in #111 dann die ermittlung von äk und gw und so. d.h. der [erste kommentar](https://github.com/PM-Dungeon/PM-Lecture/issues/110#issue-1138631992) und @Tobias321 [vorschlag](https://github.com/PM-Dungeon/PM-Lecture/issues/110#issuecomment-1047571427) passen besser zu #111 ...

**Comment by Tobias321** [comment]
Ok, dann könnte man hier klassische das Einfügen und Entfernen in eine `List` bzw. `ArrayList` testen.

`@Before`/`init()`: `ArrayList` erstellen,
`@Test`: einfügen usw.,
ggf. `assume` (innerhalb von Test): leer usw.

Das ist vielleicht nicht so spannend, aber es vermittelt die in https://github.com/PM-Dungeon/PM-Lecture/issues/110#issuecomment-1047808011 genannten Dinge...

**Comment by cagix** [comment]
ja, macht sinn. schlag mal was vor (eine erste skizze).

**Comment by Tobias321** [comment]
Testen Sie die `add`- und `remove`-Methode einer `ArrayList` mit JUnit (4.x oder 5.x).

Erstellen Sie im Paket `test` eine Testklasse `ArrayListTest` mit dem Attribut `private ArrayList<String> list;`. `list` ist dabei Ihre zu testende Klasse.

Deklarieren Sie die Methoden `setUp` und `tearDown`. Initialisieren Sie `list` innerhalb von von `setUp` und fügen Sie zwei Elemente (`"1"` und `"2"`) hinzu. Stellen Sie mit `assumeTrue` sicher, dass `list` genau zwei Elemente enthält.

Deklarieren Sie nun die Testmethoden `test_add` und `test_remove`. Testen Sie innerhalb dieser Testmethoden, ob ein Element korrekt eingefügt wird und korrekt entfernt wird. Überprüfen Sie dafür den Rückgabewert von `add` und `remove` sowie die Zustände von `list` vor und nach dem Einfügen bzw. Entfernen.

*Hinweis:* Verwenden Sie innerhalb der Testmethoden nicht die `assume...`-Methoden, weil diese lediglich einen Vorbedingungstest darstellen.
