### ISSUE TITLE
Konzeptaufgabe: JUnit Advanced

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#111]
Idee/alte Aufgabe: 

Der RSV Flotte Speiche hat in seiner Mitgliederverwaltung (`rsvflottespeiche.MitgliederVerwaltung`)
die Methode `beitritt` implementiert. Diese dient dazu, neue Mitglieder im Radsportverein aufzunehmen.

Details zum Verhalten der Methode entnehmen Sie bitte dem Javadoc-Kommentar an der vorgegebenen Methode.

1. Führen Sie eine Äquivalenzklassenanalyse durch und geben Sie die gefundenen Äquivalenzklassen (*ÄK*)
   an: laufende Nummer, Definition (Wertebereiche o.ä.), kurze Beschreibung (gültige/ungültige ÄK, Bedeutung).

2. Führen Sie zusätzlich eine Grenzwertanalyse durch und geben Sie die jeweiligen Grenzwerte (*GW*) an.

3. Erstellen Sie aus den ÄK und GW wie in der Vorlesung diskutiert Testfälle. Geben Sie pro Testfall (*TF*)
   an, welche ÄK und/oder GW abgedeckt sind, welche Eingaben Sie vorsehen und welche Ausgabe Sie erwarten.

   [Erstellen Sie separate (zusätzliche) TF für die GW, d.h. integrieren Sie diese nicht in die ÄK-TF.]{.hinweis}

4. Implementieren Sie die Testfälle in JUnit (JUnit 4 oder 5). Fassen Sie die Testfälle der gültigen ÄK
   in einem parametrisierten Test zusammen. Für die ungültigen ÄKs erstellen Sie jeweils eine eigene
   JUnit-Testmethode. Beachten Sie, dass Sie auch die Exceptions testen müssen.

**Comment by Tobias321** [comment]
Eine Bank berechnet den Zinssatz für ein Konto basierend auf dem Kontostand (Guthaben) und dem Alter des Kunden:

-   Bis einschließlich 100 EUR Guthaben gibt es 1% Zinsen,
-   bis einschließlich 1000 EUR Guthaben gibt es 3% Zinsen, und
-   darüber gibt es 5% Zinsen

(jeweils für das gesamte Guthaben).

Falls der Kunde ein Kind ist (Alter kleiner als 5 Jahre), bekommt er zusätzlich einen Bonus von 0.5%.
Falls der Kunde ein Rentner ist (Alter größer/gleich 65 Jahre), bekommt er zusätzlich einen Bonus von 1%.


Implementieren Sie eine Methode, die basierend auf dem Kontostand und dem Alter des Kunden den Gesamtzinssatz
(Zinsen plus Bonus) zurückliefert. Das Guthaben und das Alter des Kunden können Sie entweder als Parameter
(beides `int`) in der Methode oder als Attribute in der Klasse implementieren, den Namen entsprechend als `String`.

Führen Sie eine Äquivalenzklassenanalyse durch und erstellen Sie daraus Testfälle. Führen Sie nun zusätzlich
eine Grenzwertanalyse durch und ergänzen Sie die Testfälle. Dokumentieren Sie die Ergebnisse der Äquivalenzklassen-
und Grenzwertanalyse nachvollziehbar.

Implementieren Sie die ermittelten Testfälle (eine Testmethode pro Testfall) mit JUnit (4.x oder 5.x).
Implementieren Sie zusätzlich *eine* Testmethode, in der alle ermittelten positiven Testfälle als ein *parametrisierter Test*
implementiert sind.

**Comment by Tobias321** [comment]
@AMatutat Wärst du damit einverstanden, wenn wir hier https://github.com/PM-Dungeon/PM-Lecture/issues/111#issuecomment-1051942845 verwenden?

**Comment by cagix** [comment]
@Tobias321 Ich denke, wir sollten einfach beide Ideen aufbereiten und vorbereiten. Welche wir dann konkret dieses Jahr einsetzen, kann ich mir dann ja noch später überlegen. 

Ich würde das hier eher abschließen wollen, da es keine neuen Ideen gibt/gab bisher und noch komplett leere Aufgaben warten.

**Comment by cagix** [comment]
RSV fehlt noch.

**Comment by AMatutat** [comment]
Was ist RSV?

**Comment by cagix** [comment]
> Was ist RSV?

https://github.com/PM-Dungeon/PM-Lecture/issues/111#issue-1138632059

**Comment by Tobias321** [comment]
> RSV fehlt noch.

Das stimmt. Das kommt, denke ich, heute oder morgen...

**Comment by Tobias321** [comment]
> Was ist RSV?

Radsportverein...

**Comment by cagix** [comment]
> yikes. Ich habe gedacht, das ist eine JUnit Technik, die noch fehlt und habe evtl. etwas zu lange danach gegooglet :D

alter, nie aufm rad gesessen?! 😱
