### ISSUE TITLE
Konzeptaufgabe: Mocking

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#112]
Idee:
Tests vorgeben die nicht laufen weil die Implementierung einer Klasse fehlt. Die Studies müssen dann Mocking verwenden um die Tests zum laufen zu bekommen

**Comment by Tobias321** [comment]
@cagix Ich hab spontan keine Idee. Mocking braucht man doch nur, wenn eine Teilfunktionalität gemockt und nicht getestet werden soll (zum Beispiel eine Datenbankanbindung oder LibGdx), weil man davon ausgehen kann, dass diese funktioniert... Also mir ist die Herangehensweise noch nicht klar.

**Comment by cagix** [comment]
@Tobias321 Die Idee ist, dass die Studis aktiv Mocking einsetzen sollen. Also brauchen wir ein Szenario mit einigen vorgegebenen Klassen und Methoden, von denen dann im Test ein paar "weg-gemockt" werden sollen. Das muss jetzt nix wahnsinnig kompliziertes sein oder gleich libGDX oder so ... 

Der einfachste Fall ist ein Methodenaufruf, der nächstkomplexere dann das Mocken einer Klasse und danach vielleicht sowas wie Vererbung?

**Comment by cagix** [comment]
Also in einer Klasse B hast Du ein Attribut vom Typ A. Die Methoden in B rufen teilweise Methoden von A auf, wobei letztere einfach nur eine "not-implemented"-Exception werfen. Getestet werden dann die Methoden von B, indem die Aufrufe der A-Methoden gemockt werden ...

**Comment by Tobias321** [comment]
Ok, ich mache mal etwas fertig. 🙂
