### ISSUE TITLE
Konzeptaufgabe: Bad Smells und Refacoring

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#113]
Idee:
Schlechten Code Vorgeben und mithilfe von Refactoring verbessern lassen.
Vorgehen muss Dokumentiert werden. Warum ist das doof? Welche Methoden wurden verwendet? 
Die Methoden sollten verwendet werden
- Extract Method
- Move Method
- Extract Class 
- Encapsulation Filed
- Pull Up
- Push down

Evtl kann man auch noch mehr machen. Vielleicht ist das interessantes dabei: https://refactoring.guru/refactoring/techniques

**Comment by CrappyAlgorithm** [comment]
Ich wollte das Issue im privaten Repo an dieses binden, allerdings startet die Nummerierung der Issues wieder bei 1. Ich weiß nun nicht wie ich die verbinden soll. Im Zweifel müsste dann der selbe Namen wie dieses Issue reichen.

**Comment by cagix** [comment]
@CrappyAlgorithm Ich dachte da an sowas wie "siehe <url-zum-original-ticket>" im ersten kommentar.

**Comment by CrappyAlgorithm** [comment]
Wie wäre der Name des privaten Repos und die Nummer des Issues? Also in diesem Fall "Sebastian Issue 1". Ich würde das in den ersten Kommentar hier im Issue hinzufügen, allerdings kann ich nicht editieren. 
Und wenn ich dann im privaten etwas fragen möchte, kann ich ja hier auf den xten Kommentar verweisen.

**Comment by cagix** [comment]
argl. sorry, irgendwie hat gh meinen kommentar kaputt gemacht. ich würde hier im privaten repo im ersten kommentar einfach die url vom ticket im lecture-repo reinkopieren, damit hast du die verlinkung.

**Comment by cagix** [comment]
@CrappyAlgorithm siehe altes vorgabe-repo. bitte den code nochmal anfassen, vielleicht einen e-roller-verleih draus machen?

wichtig wäre, dass man "encapsulate field", "rename field/method/class", "extract method" (am besten mehrfach) und "pull up" oder "push down" machen muss.

**Comment by CrappyAlgorithm** [comment]
> @CrappyAlgorithm siehe altes vorgabe-repo. bitte den code nochmal anfassen, vielleicht einen e-roller-verleih draus machen? (streaming würde aber auch gehen.)
> 
> wichtig wäre, dass man "encapsulate field", "rename field/method/class", "extract method" (am besten mehrfach) und "pull up" oder "push down" machen muss.

Ok weiß ich bescheid. Ich dachte auch schon an einen Fahrradverleih.

**Comment by cagix** [comment]
> > @CrappyAlgorithm siehe altes vorgabe-repo. bitte den code nochmal anfassen, vielleicht einen e-roller-verleih draus machen? (streaming würde aber auch gehen.)
> > wichtig wäre, dass man "encapsulate field", "rename field/method/class", "extract method" (am besten mehrfach) und "pull up" oder "push down" machen muss.
> 
> Ok weiß ich bescheid. Ich dachte auch schon an einen Fahrradverleih.

das geht auch :)  u-bahn-gurken, commuter, rennräder, gravel, mtb ... passt 👍

**Comment by cagix** [comment]
oh, und bromptons!
