### ISSUE TITLE
Konzeptaufgabe: Generics 2

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#115]
Hier sollte es um Polymorphie, Bounds & Wildcards (und Type Erasure) 

siehe https://github.com/PM-Dungeon/Homework-Solutions/pull/19

**Comment by cagix** [comment]
@AHeinisch @jedi101 Was ist denn hier der Stand?

**Comment by jedi101** [comment]
@cagix - Bin da dran. Sobald es einen neuen Stand gibt der vorzeigbar ist setze ich ein neues Review an.

**Comment by cagix** [comment]
@jedi101 Bitte gib mal etwas Gummi -- die Aufgabe sollte letzte Woche fertig sein!

**Comment by cagix** [comment]
@AMatutat Bitte zur Not mit einspringen. Das sollte längst durch sein ...

**Comment by jedi101** [comment]
@cagix - Gebe Gummi.

**Comment by AMatutat** [comment]
@jedi101 status bericht?

**Comment by jedi101** [comment]
@AMatutat - Gibt etwas neues. Siehe hier. https://github.com/PM-Dungeon/Alex/pull/3

**Comment by cagix** [comment]
@AMatutat @jedi101 Wir sind jetzt hier: https://github.com/PM-Dungeon/Homework-Solutions/pull/19
