### ISSUE TITLE
Konzeptaufgabe: Funktionsinterfaces, Lambdas und Methodenreferenzen

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#117]
FunktionsInterface,Lambdas, Methoderefernezen
	- steck nen lambda in ne Methode
	- steck ne Methodereferenz in ne Methode
	- Funktionsinterface selber schreiben
	- code vorgeben?
	- ggf. alte Aufgaben im E-Assements

---

Idee: einfache Klasse vorgeben, klassische for-Schleife über eine Collection mit dieser Klasse

Ziel: Umformen der for-Schleife in die "neue" kompakte Syntax und Durchspielen der Varianten der Methoden-Referenz plus 1x Lambda (=> Syntax lernen, Funktionsinterface definieren)

**Comment by cagix** [comment]
@CrappyAlgorithm @AMatutat Haben wir schon irgendwo was für diese Aufgabe oder bin ich nur zu blöd zum Suchen? Im Homework-Repo sehe ich nix (weder unter "offen" noch unter "geschlossen")?

**Comment by AMatutat** [comment]
@cagix mir ist noch nichts zu Gesicht gekommen.

**Comment by cagix** [comment]
mist.

**Comment by CrappyAlgorithm** [comment]
> @CrappyAlgorithm @AMatutat Haben wir schon irgendwo was für diese Aufgabe oder bin ich nur zu blöd zum Suchen? Im Homework-Repo sehe ich nix (weder unter "offen" noch unter "geschlossen")?

Ich wollte da morgen ran, ich weiß ist Feiertag, aber egal. Bis wann muss das denn fertig sein? Kann das morgen dann soweit komplett machen und dann Freitag/Samstag den Feinschliff, nachdem du dir das angeschaut hast. Wenn meine Stunden nicht reichen, kann ich das auch einfach auf die nächste Woche mit anrechnen.

**Comment by cagix** [comment]
> > @CrappyAlgorithm @AMatutat Haben wir schon irgendwo was für diese Aufgabe oder bin ich nur zu blöd zum Suchen? Im Homework-Repo sehe ich nix (weder unter "offen" noch unter "geschlossen")?
> 
> Ich wollte da morgen ran, ich weiß ist Feiertag, aber egal. Bis wann muss das denn fertig sein? Kann das morgen dann soweit komplett machen und dann Freitag/Samstag den Feinschliff, nachdem du dir das angeschaut hast. Wenn meine Stunden nicht reichen, kann ich das auch einfach auf die nächste Woche mit anrechnen.

Naja: Der Stoff ist nächste Woche dran, also sollte das Material nach Möglichkeit Ende dieser Woche released werden.

**Comment by AMatutat** [comment]
- [ ] PR Lecture Repo
- [ ] PR Vorgabe Repo
- [ ] Merge
