### ISSUE TITLE
Konzeptaufgabe: Stream-Api

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#118]
@cagix du hattest dir gestern was ausgedacht, ich hab mir "siehe Screenshot" aufgeschrieben und den Screenshot nicht gespeichert..... 
Magst du das ganz kurz ausführen?

**Comment by cagix** [comment]
oha, dann muss ich mir jetzt was sinnvolles aus den fingern saugen? okay, einfach so in einer fiktiven sprache:

```
ArrayList<Foo> x,y
for i in x:
    if pred(i):
        y.add(foo(i)
```

daraus dann

```
y = x.toStream().filter(pred).map(foo).collect();
```

also den oberen teil vorgeben und in den unteren teil umformen lassen. ach ja, und natürlich gültiges java draus machen (lassen) :)
