### ISSUE TITLE
Konzeptaufgabe: RegExp

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#119]
Idee:
Früher hatten wir den Lexer, der ist aber zu groß. Aber wir könnten den Zerlegen. Ein Programm das Eingaben annimmt und dann Regexp nutzt um zu prüfen, ob die Eingabe eine JavaDoc Kommentar, eine Annoation, eine Schleife etc. ist. 

- einfacher String (Keywords)
- Multi-Line
- Verschachtelt (im Kommentar auch noch Javadoc-Annotationen)
- Gruppen 
- Backreferences (?)

## Alter Lexer (damals 12 Punkte) 
Im ersten Schritt muss der Java-Quelltext in passende Token aufgeteilt werden.
Ein solches Programm wird auch Lexer genannt und stellt die erste Phase eines
Parsers dar.^[Der nächste Schritt wäre dann der Aufbau eines Syntaxbaumes und
das Prüfen der korrekten Syntax. Dies ist zwar noch viel spannender, geht aber
leider deutlich über Ihre aktuellen Kenntnisse in Theoretischer Informatik
hinaus. Darüber sprechen wir im Master in "Compilerbau" :-)]

Beispiel: Der Java-Quellcode
```java
// total irre: public void foo()
public void foo(String s) {}
```
enthält die Token \fbox{\texttt{// total irre: public void foo()}},
\fbox{\texttt{public}}, \fbox{\texttt{void}} und \fbox{\texttt{foo(String s) \{\}}}.

Ihr Lexer erhält den zu untersuchenden Quellcode als String über den Aufruf
von `Lexer#tokenize`. Er muss dann mit der Methode `Lexer#testTokens`
schrittweise prüfen, ob ein bestimmtes Token am Anfang des Strings
vorliegt. Falls dies so ist, wird die gefundene Zeichenkette aus dem String
entfernt und ein entsprechendes Token-Objekt in der Ergebnisliste gespeichert.
Dies wird so lange wiederholt, bis der String komplett abgearbeitet ist.
Anschließend wird die Ergebnisliste der erkannten Token zurückgeliefert.

Ihr Lexer soll folgende Token unterscheiden und erkennen:

1.  Klasse `Comment`: Einzeilige Kommentare (beginnend mit `//` bis zum Zeilenende)

2.  Klasse `MultilineComment`: Mehrzeilige Kommentare (alles zwischen `/*` und `*/`)

3.  Klasse `JavaDocComment`: Java-Doc-Kommentare (alles zwischen `/**` und `*/`)

4.  Klasse `StringContent`: Strings (alles zwischen `"` und  `"`)

5.  Klasse `CharacterContent`: Zeichen (alles zwischen `'` und  `'`), zu behandeln wie Strings

6.  Klasse `KeyWord`: Ausgewählte Java-Schlüsselwörter

    Als Java-Schlüsselwörter müssen Sie mindestens implementieren: `import`,
    `class`, `public`, `private`, `final`, `static`, `return`, `if`, `else`,
    `while`, `try`, `catch`, `finally`. Es steht Ihnen frei, Pattern für weitere
    Schlüsselwörter zu implementieren.

7.  Klasse `Annotation`: Einfache Annotationen (ohne Parameter o.ä.), d.h. Zeichenketten
    beginnend mit einem `@`, welches auf eine Wortgrenze folgt, bis zur nächsten Wortgrenze

8.  Klasse `NewLine`: Nutzen Sie zur Darstellung von Zeilenumbrüchen ein zusätzliches spezielles
    Zeilenumbruch-Token

    Diese Tokenklasse hat eine höhere Priorität als das "Catch-All"-Token, muss
    also vor diesem geprüft werden. Zeilenumbrüche innerhalb von mehrzeiligen
    Kommentaren gehören aber nach wie vor zum Kommentartext!

9.  Klasse `CatchAll`: Sonstigen Text, d.h. alle restlichen Zeichen zwischen zwei Token der
    eben erklärten Art

    Dabei wird **zeichenweise** gearbeitet, d.h. pro Zeichen wird ein Objekt
    der Klasse `CatchAll` angelegt.

Für jedes Token gibt es eine entsprechende Token-Klasse mit dem passenden
regulären Ausdruck, der die jeweilige Zeichenkette erkennt.^[Dies ist
im Compilerbau eher unüblich, dient hier aber zum Üben mit unterschiedlichen
regulären Ausdrücken.] Die Tokenklassen bilden eine Klassenhierarchie mit
gemeinsamer abstrakter Basisklasse.

Halten Sie dabei die Abbildung \ref{fig.uml} dargestellten Schnittstellen
bzw. Klassenhierarchien ein.^[Sie können wie immer eigene Attribute und
Methoden ergänzen.]

---

siehe https://github.com/PM-Dungeon/Homework-Solutions/pull/37

**Comment by AMatutat** [comment]
@cagix Könnten wir nicht theoretisch die alte Lösung vom Lexer vorgeben und nur die Regulären Ausdrücke entfernen. Dann währe der ganze Overhead weg und die Aufgabe würde sich wirklich nur auf Regexp konzentrieren. Verliert dann natürlich einiges an Charm.

**Comment by cagix** [comment]
puh. das könnte man machen, aber dann sollten wir auch ne "richtige" lösung quasi als lückentext vorgeben, so dass der spass dann nach dem einsetzen der regexps funktioniert und ne art highlighting macht. sowas hab ich aber nicht -- aber @TGrothe könnte sowas vielleicht erstellen.

aber ohne diese lösung als vorgabe ist das einfach nur irre komplex und hat wenig charme.

**Comment by TGrothe** [comment]
@cagix @AMatutat Das kann ich in Angriff nehmen. ;)

Als gesucht ist also eine Lösung, aber quasi als "Lückentext".

**Comment by AMatutat** [comment]
> Als gesucht ist also eine Lösung, aber quasi als "Lückentext".

Genau. Es könnte der einfachste Weg sein, den Lexer zu implementieren (also quasi die Lösung) und daraus die Vorgaben ableiten.
