### ISSUE TITLE
Konzeptaufgabe: Buildscripts

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#123]
siehe https://github.com/PM-Dungeon/Homework-Solutions/pull/13

---

Aufgabe: 
In dieser Aufgaben sollen Sie ein eigenes Gradle-Buildscript schreiben. 
Ihr Buildscript muss folgende Tasks besitzen
- run: Startet das Programm
- build: Kompiliert 
- jar: Baut eine `.jar`-File in `output/jars/`
- clear: Löscht alle temporären Dateien (outputs) 

Schreiben Sie ein kleines Dummy-Programm, um die Funktionen Ihres Buildscriptes zu demonstrieren.

**Comment by AMatutat** [comment]
@cagix Ich habe eine grobe Aufgabe getippert, fehlt dir irgendwas wichtiges?

**Comment by cagix** [comment]
> @cagix Ich habe eine grobe Aufgabe getippert, fehlt dir irgendwas wichtiges?

Hmmm, _wo_ hast Du denn die Aufgabe getipptert?

**Comment by cagix** [comment]
Oh, ganz oben im ersten Kommentar, oder?

Im Prinzip geht das in die gesuchte Richtung. 

Ein paar Fragen bleiben aber:
- Müssen wir mehr zum Dummy-Programm sagen? 
- Werden die Targets nicht bereits durch Gradle bereitgestellt (`build` beispielsweise)?
- Sollten wir noch Abhängigkeiten mit auflösen (lassen)?
- Müssen wir Konventionen beachten?

**Comment by AMatutat** [comment]
> Oh, ganz oben im ersten Kommentar, oder?

Yep. 

> Müssen wir mehr zum Dummy-Programm sagen?

Eigentlich ist mir recht egal, was die da machen. Hello World oder so. Geht ja nur darum, dass man was zum Ausführen hat. 

> Werden die Targets nicht bereits durch Gradle bereitgestellt (build beispielsweise)?

Ich glaube die meisten ja, aber man muss die config entsprechend Konfigurieren. Hmm... wenn die einfach über die IDE ein Gradle-Projekt erstellen, ist das alles hinfällig... 

Evtl. geben wir doch Code vor und die müssen das Skript schreiben. Dann kann man da auch noch ein paar Abhängigkeiten einbauen. 

> Müssen wir Konventionen beachten?

Äh öh... @Tobias321 kennst du welche? Mein Wissen über Gradle ist begrenzt.

**Comment by cagix** [comment]
das ist halt die sache. im grunde kriegen die von eclipse oder ij eine default-konfig, oder eben über `gradle init` (siehe https://docs.gradle.org/current/samples/sample_building_java_applications.html).

der reiz wäre, hier irgendwie noch manuell abhängigkeiten reinzubauen, die man nicht direkt von eclipse/ij geschenkt bekommt. vielleicht irgendeine lib nur zum testen, irgendwas anderes zum bauen, ... 

und vielleicht ein non-standard repository anzusprechen (https://docs.gradle.org/current/userguide/declaring_repositories.html). 

---

oder wir geben schlicht was vor: ein mini-projekt, was aus ner "lib" und ner "app" besteht und wofür die manuell eine konfig erzeugen sollen in der abgabe.

**Comment by AMatutat** [comment]
ich geh nochmal ans Zeichenbrett.

**Comment by Tobias321** [comment]
> > Müssen wir Konventionen beachten?
> 
> Äh öh... @Tobias321 kennst du welche? Mein Wissen über Gradle ist begrenzt.

Also eigentlich funktioniert die `build.gradle` nur dann, wenn man die richtige Reihenfolge der "Entities" einhält... andernfalls wird sich Gradle beim Bauen/Starten beschweren und einen Fehler ausgeben. Innerhalb bestimmter "Entity-Gruppen" ist die Reihenfolge aber frei wählbar. Man könnte sich darauf festlegen, nur '-Zeichen oder nur "-Zeichen für String-Literale zu verwenden. Sonst fällt mir spontan aber keine Konvention ein...

Für geteilte Konfigurationen gibt es wohl "Konventionen/Best ways": [Link](https://blog.jdriven.com/2021/02/gradle-goodness-shared-configuration-with-conventions-plugin/)

**Comment by Tobias321** [comment]
> Tobias321 Kannst du dafür eine grobe Lösung tippern?

Ich denke schon :)

**Comment by cagix** [comment]
> Daher würde ich Vorschlagen, die sollen sich das `core` Projekt anschauen und den Tutoren im Praktikum erklären, was dort zu sehen ist und was das alles bedeutet.

finde ich gar nicht so schlecht. aber: ist das denn komplex genug?

**Comment by AMatutat** [comment]
> finde ich gar nicht so schlecht. aber: ist das denn komplex genug?

Es ist zumindest Realistisch. Komplex kannst du dann in der Prüfung werden. ^^

**Comment by cagix** [comment]
@AMatutat @Tobias321 Was ist hier der Stand? Kriegen wir das Ding in den nächsten 1..3 Tagen zu?

**Comment by Tobias321** [comment]
> @AMatutat @Tobias321 Was ist hier der Stand? Kriegen wir das Ding in den nächsten 1..3 Tagen zu?

Ich bräuchte eine (genaue) Aufgabenstellung, damit ich weiß, worauf ich bei der Lösung achten sollte...

**Comment by cagix** [comment]
> > @AMatutat @Tobias321 Was ist hier der Stand? Kriegen wir das Ding in den nächsten 1..3 Tagen zu?
> 
> Ich bräuchte eine (genaue) Aufgabenstellung, damit ich weiß, worauf ich bei der Lösung achten sollte...
> 
> Edit: Muster angepasst...

@AMatutat kannst Du hier bitte weiter helfen?

**Comment by AMatutat** [comment]
Bastel ich heute

**Comment by cagix** [comment]
@AMatutat @Tobias321 Bitte die Aufmerksamkeit jetzt hierhin lenken :)

**Comment by cagix** [comment]
Damit es hier endlich mal voran geht, mache ich die Aufgabe halt selber.

**Comment by AMatutat** [comment]
> Damit es hier endlich mal voran geht, mache ich die Aufgabe halt selber.

Hä? Wir haben doch https://github.com/PM-Dungeon/PM-Lecture/pull/419

**Comment by cagix** [comment]
> > Damit es hier endlich mal voran geht, mache ich die Aufgabe halt selber.
> 
> Hä? Wir haben doch [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13)

ja. den habe ich grad erstellt, damit ich endlich diese verk*ckte aufgabe zu kriege und woche 4 fertig kriege :/

**Comment by cagix** [comment]
wir haben echt keine zeit für diese trödelei

**Comment by cagix** [comment]
@AMatutat In https://github.com/PM-Dungeon/Homework-Solutions/pull/13 sollte eigentlich die Aufgabe und die Lösung erstellt werden. Da die Lösung aber irgendwie nicht voran kommt, wird die Aufgabe selbst auch nicht fertig. Ich muss diese Woche (also heute) aber die Aufgabe ins ILIAS packen. Also habe ich mir den Text genommen und den PR #419 in diesem Repo erstellt, quasi zu früh.

**Comment by AMatutat** [comment]
Workflowtechnisch find ich das immer noch komisch. Du hättest die Aufgabe auch in https://github.com/PM-Dungeon/Homework-Solutions/pull/13 verfeinern können + Review und dann hierhin übertragen.
Naja egal, am Ende müssen wir nur daran denken #419 nach https://github.com/PM-Dungeon/Homework-Solutions/pull/13 zu übertragen.

**Comment by cagix** [comment]
> Workflowtechnisch find ich das immer noch komisch. Du hättest die Aufgabe auch in [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) verfeinern können + Review und dann hierhin übertragen.
> Naja egal, am Ende müssen wir nur daran denken #419 nach [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) zu übertragen.

Hmmm, das ist aber der Branch von @Tobias321, und er ist da aktiv am arbeiten (glaube ich). Wenn ich ihm dort die Datei unterm Hintern wegreisse, geht doch auch wieder alles kaputt. Und die Überarbeitung über Kommentare oder Reviews zu machen, wo die Hälfte wieder untergeht/übersehen wird, ist auch viel zu zeitraubend.

**Comment by cagix** [comment]
> > Workflowtechnisch find ich das immer noch komisch. Du hättest die Aufgabe auch in [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) verfeinern können + Review und dann hierhin übertragen.
> > Naja egal, am Ende müssen wir nur daran denken #419 nach [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) zu übertragen.
> 
> Hmmm, das ist aber der Branch von @Tobias321, und er ist da aktiv am arbeiten (glaube ich). Wenn ich ihm dort die Datei unterm Hintern wegreisse, geht doch auch wieder alles kaputt. Und die Überarbeitung über Kommentare oder Reviews zu machen, wo die Hälfte wieder untergeht/übersehen wird, ist auch viel zu zeitraubend.

Normalerweise passt das ja auch: Man skizziert im Lösungsrepo die Aufgabe, erstellt die Lösung, erstellt daraus ggf. die Vorgaben und passt die Aufgabe an die Lösung an. Aber in diesem konkreten Fall zieht sich das einfach, und ich sehe da grad kein Ende. Und @Tobias321 einfach in seinen Branch/PR reinzucomitten ist auch nicht wirklich schick ...

**Comment by Tobias321** [comment]
> > > Workflowtechnisch find ich das immer noch komisch. Du hättest die Aufgabe auch in [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) verfeinern können + Review und dann hierhin übertragen.
> > > Naja egal, am Ende müssen wir nur daran denken #419 nach [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) zu übertragen.
> > 
> > 
> > Hmmm, das ist aber der Branch von @Tobias321, und er ist da aktiv am arbeiten (glaube ich). Wenn ich ihm dort die Datei unterm Hintern wegreisse, geht doch auch wieder alles kaputt. Und die Überarbeitung über Kommentare oder Reviews zu machen, wo die Hälfte wieder untergeht/übersehen wird, ist auch viel zu zeitraubend.
> 
> Normalerweise passt das ja auch: Man skizziert im Lösungsrepo die Aufgabe, erstellt die Lösung, erstellt daraus ggf. die Vorgaben und passt die Aufgabe an die Lösung an. Aber in diesem konkreten Fall zieht sich das einfach, und ich sehe da grad kein Ende. Und @Tobias321 einfach in seinen Branch/PR reinzucomitten ist auch nicht wirklich schick ...

Im Moment komme ich damit nicht richtig voran... also gerne reincomitten ;)

**Comment by cagix** [comment]
> > > > Workflowtechnisch find ich das immer noch komisch. Du hättest die Aufgabe auch in [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) verfeinern können + Review und dann hierhin übertragen.
> > > > Naja egal, am Ende müssen wir nur daran denken #419 nach [PM-Dungeon/Homework-Solutions#13](https://github.com/PM-Dungeon/Homework-Solutions/pull/13) zu übertragen.
> > > 
> > > 
> > > Hmmm, das ist aber der Branch von @Tobias321, und er ist da aktiv am arbeiten (glaube ich). Wenn ich ihm dort die Datei unterm Hintern wegreisse, geht doch auch wieder alles kaputt. Und die Überarbeitung über Kommentare oder Reviews zu machen, wo die Hälfte wieder untergeht/übersehen wird, ist auch viel zu zeitraubend.
> > 
> > 
> > Normalerweise passt das ja auch: Man skizziert im Lösungsrepo die Aufgabe, erstellt die Lösung, erstellt daraus ggf. die Vorgaben und passt die Aufgabe an die Lösung an. Aber in diesem konkreten Fall zieht sich das einfach, und ich sehe da grad kein Ende. Und @Tobias321 einfach in seinen Branch/PR reinzucomitten ist auch nicht wirklich schick ...
> 
> Im Moment komme ich damit nicht richtig voran... also gerne reincomitten ;)

ja. nein. das ist nicht der richtige weg. (aber ich weiss auch nicht, was hier besser wäre.)

**Comment by AMatutat** [comment]
> ja. nein. das ist nicht der richtige weg. (aber ich weiss auch nicht, was hier besser wäre.)

Einen Sub-Branch von Tobis Branch anlegen und dann ein PR aufmachen?

**Comment by cagix** [comment]
> > ja. nein. das ist nicht der richtige weg. (aber ich weiss auch nicht, was hier besser wäre.)
> 
> Einen Sub-Branch von Tobis Branch anlegen und dann ein PR aufmachen?

ja, das wäre korrekt(er). aber wie ich uns kenne, verlagert sich die diskussion dann in den sub-pr ... und dann hast du drei stränge: das eigentliche ticket, den ersten pr und den pr in den pr. hmmm.
