### ISSUE TITLE
Konzeptaufgabe: Multithreading

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#124]
Idee:
Das Dungeonframework verwenden und selber ein kleinen Hamstersimulator basteln (das müssten wir machen)

Dungeon eher/besser nicht!

https://github.com/SQAHamster/plain-java-hamster (?!)
https://github.com/ElJanogu/hamsterSimulator (??)

**Comment by TGrothe** [comment]
Wenn du hierbei (oder bei einer anderen Aufgaben) Hilfe benötigst, bitte Bescheid geben. Mit Multithreading/Threads kenn ich mich eigentlich ganz gut aus. Mit dem Hamster-Simulator hatte ich auch schon mal herumgespielt.^^

**Comment by TGrothe** [comment]
> @TGrothe kannst dir das Ticket auch gerne schnappen. Dachte nur evtl. bist du im Dungeon so genug ausgelastet. Wie du willst

Hm, aber eigentlich hab ich auch mit dem Review und Dungeon zu tun ;)

**Comment by CrappyAlgorithm** [comment]
@AMatutat mir kam grade eine simple Idee, die auf eine visuelle Darstellung verzichten kann.

Mehrere Threads sollen eine Zahl hochzählen, ohne Synchronisierung würden die aber kaum vorwärts kommen, weil sie den Zähler oft zu früh lesen und dann gegenseitig überschreiben.
Als Erweiterung könnte man dann alle Threads in das selbe Log File schreiben lassen. Da müsste man dann noch überlegen, ob alle Threads einen eigenen Logger, oder zusammen einen verwenden sollten. Ich weiß nur nicht, ob der Logger vielleicht sogar solche Fälle selbst abfängt. Falls ja müsste man einfach die Verwendung per direktem Dateizugriff vorgeben.

**Comment by CrappyAlgorithm** [comment]
> @AMatutat mir kam grade eine simple Idee, die auf eine visuelle Darstellung verzichten kann.
> 
> Mehrere Threads sollen eine Zahl hochzählen, ohne Synchronisierung würden die aber kaum vorwärts kommen, weil sie den Zähler oft zu früh lesen und dann gegenseitig überschreiben. Als Erweiterung könnte man dann alle Threads in das selbe Log File schreiben lassen. Da müsste man dann noch überlegen, ob alle Threads einen eigenen Logger, oder zusammen einen verwenden sollten. Ich weiß nur nicht, ob der Logger vielleicht sogar solche Fälle selbst abfängt. Falls ja müsste man einfach die Verwendung per direktem Dateizugriff vorgeben.

Oder etwas eleganter als Haushaltskasse, auf die mehrere Threads unabhängig zugreifen. Das könnte man dann auch über Tests validieren.

**Comment by cagix** [comment]
> @AMatutat mir kam grade eine simple Idee, die auf eine visuelle Darstellung verzichten kann.
> 
> 
> 
> Mehrere Threads sollen eine Zahl hochzählen, ohne Synchronisierung würden die aber kaum vorwärts kommen, weil sie den Zähler oft zu früh lesen und dann gegenseitig überschreiben.
> 
> Als Erweiterung könnte man dann alle Threads in das selbe Log File schreiben lassen. Da müsste man dann noch überlegen, ob alle Threads einen eigenen Logger, oder zusammen einen verwenden sollten. Ich weiß nur nicht, ob der Logger vielleicht sogar solche Fälle selbst abfängt. Falls ja müsste man einfach die Verwendung per direktem Dateizugriff vorgeben.

ja, aber das ist das beispiel aus der vorlesung :)

**Comment by cagix** [comment]
ich finde die "hampster" im dungeon eigentlich eine nette idee. ich glaube, alle dinge sind bereits da, um die hamster damit zu simulieren. 

die frage ist nur: wie verträgt sich libgdx mit multi-threading?

man könnte eine minimale welt mit nem kleinen level und einfachen monstern (kein held?!) vorgeben, die durch den dungeon nur angezeigt werden und die per multithreading was tun, etwa felder betreten und dort dinge aufsammeln.

**Comment by CrappyAlgorithm** [comment]
> ich finde die "hampster" im dungeon eigentlich eine nette idee. ich glaube, alle dinge sind bereits da, um die hamster damit zu simulieren.
> 
> die frage ist nur: wie verträgt sich libgdx mit multi-threading?
> 
Ich glaube das möchte ich garnicht ausprobieren 😀 

> man könnte eine minimale welt mit nem kleinen level und einfachen monstern (kein held?!) vorgeben, die durch den dungeon nur angezeigt werden und die per multithreading was tun, etwa felder betreten und dort dinge aufsammeln.

Es würde sich vermutlich anbieten, wenn man die Logik direkt auch als eigenen Thread realisiert, der dann die Entities manipuliert und das Dungeon dient dann ausschließlich zur Darstellung. Wenn das Dungeon nur lesend auf die zu zeichnenden Entites zugreift bräuchte man ja nichtmal eine Synchronisierung. Selbst wenn einzelne Entities dann beim Rendern nur partiell aktualisiert wurden, betrifft es nur die Darstellung und dann auch nur wenige Frames. Korrigiert mich falls ich etwas übersehen habe.

Und für die Logik, bzw. die Schnittstelle für die Studierenden, kann man sich ja dann auch vom Hamstersimulator inspirieren lassen.
Anstatt Hamster fände ich übrigens Monster, die Edelsteine sammel und ablegen, schöner.

**Comment by cagix** [comment]
> > man könnte eine minimale welt mit nem kleinen level und einfachen monstern (kein held?!) vorgeben, die durch den dungeon nur angezeigt werden und die per multithreading was tun, etwa felder betreten und dort dinge aufsammeln.
> 
> Es würde sich vermutlich anbieten, wenn man die Logik direkt auch als eigenen Thread realisiert, der dann die Entities manipuliert und das Dungeon dient dann ausschließlich zur Darstellung. 

Genau das war die Idee. Trotzdem müsste man das mal ausprobieren bzw. recherchieren, ob da irgendwer vielleicht schon mal was in die Richtung gemacht hat.


> Wenn das Dungeon nur lesend auf die zu zeichnenden Entites zugreift bräuchte man ja nichtmal eine Synchronisierung. Selbst wenn einzelne Entities dann beim Rendern nur partiell aktualisiert wurden, betrifft es nur die Darstellung und dann auch nur wenige Frames. 

Das wäre die Annahme, dass das so klappt. Vermutlich sollte man auf ausführliche Animationen verzichten. Aber letztlich läuft die Main-Loop, die die Entities auf den aktuellen Positionen zeichnet. Wenn die sich dazwischen bewegen, ist halt die gezeichnete Position kurzzeitig falsch. Aber das sollte eigentlich nicht stören.

Es muss nur sicher gestellt werden, dass die Threads ausschließlich ihren internen Zustand parallel modifizieren und sich gegenseitig synchronisieren - ich denke an das Betreten von Feldern und das Aufsammeln von Items: Hier müssten sich die Threads untereinander synchronisieren und dann eben ihre Position aktualisieren oder dem Item "sagen", dass es jetzt "aufgesammelt" ist. Aber das Auswerten dieser Daten und das Anzeigen der Daten muss dann weiterhin in der Main-Loop passieren.



> Und für die Logik, bzw. die Schnittstelle für die Studierenden, kann man sich ja dann auch vom Hamstersimulator inspirieren lassen. Anstatt Hamster fände ich übrigens Monster, die Edelsteine sammel und ablegen, schöner.

Ja klar. Aber das ist doch nur ein Konfigurationsdetail. Wegen mir können es auch Tintenfische oder Katzen oder Marsmännchen sein ;)

**Comment by AMatutat** [comment]
@CrappyAlgorithm Gestern hast du eine Idee für ein Bankkonto geptichts. Das bitte machen

**Comment by cagix** [comment]
@AMatutat @CrappyAlgorithm Kriegen wir das bis Montag hin?

**Comment by AMatutat** [comment]
@cagix Jetzt hab ich wieder label Kopfweh. Das muss doch erst die Woche danach fertig sein. Oder?

**Comment by cagix** [comment]
der stoff ist für die kommende woche. also auch das blatt.

**Comment by AMatutat** [comment]
Argh.....
Warum verwirrt mich das immer so?
Aber ja, kriegen wir schon hin..... muss ja

**Comment by cagix** [comment]
naja, dienstag reicht vermutlich auch, da dort ja die aufgabe von dieser woche abgegeben wird. aber ab mittwoch muss man damit rechnen, dass die studis das bearbeiten wollen ... d.h. dienstag 18 uhr sollte die aufgabe spätestens online sein :)

**Comment by AMatutat** [comment]
@AHeinisch @CrappyAlgorithm schafft ihr das heute, oder soll/muss ich das übernehmen?

**Comment by AHeinisch** [comment]
Also ich war mir nicht sicher was ich genau dazu beitragen soll.  Ich hatte ja eigentlich nur eine Idee für das synchronized gegeben. Da ich leider bisher noch nichts von @CrappyAlgorithm gehört habe, weiß ich leider nicht die restlichen Teile. Ich könnte, von dem, was ich verstanden, habe eine Idee für diese Aufgabe basteln.

**Comment by AHeinisch** [comment]
Entwickeln Sie eine Multithreading Anwendung für ein Bankensystem.

Der Hauptthread soll einmal in der Sekunde neue Transaktionen erstellen, für 10-mal. (Vorgabe, welche kontinuierlich Daten erstellt)
Für jedes Konto soll ein eigener Thread existieren, welcher die Berichte erstellt und diese dann in die dazugehörige Datei schreibt.

Die Kontos sollen Berichte erstellen können.
Bericht der letzten 30 "Tage"
Bericht eines Monats

ein Bericht besteht aus:
```
Datum start
Datum ende
Kontostand am start
Transaktionen
Kontostandänderung
Kontostand am ende
```

Zusätzlich soll ein Logger alle Informationen in eine Datei schreiben (hier könnte synchronized eingesetzt werden können).

**Comment by cagix** [comment]
> Der Hauptthread soll einmal in der Sekunde neue Transaktionen erstellen, für 10-mal. 

Hier würde ich eher lauter eigenständige Akteure (Threads) sehen, die irgendwelche Transaktionen erstellen und parallel in der Bank einreichen.

Dann müsste man in der Bank die Zugriffe auf die Konten synchronisieren.


> Für jedes Konto soll ein eigener Thread existieren, welcher die Berichte erstellt und diese dann in die dazugehörige Datei schreibt.

Bank erstellt Thread-Pool (Executor-API) und lässt darüber für jedes Konto die Berichte parallel erstellen.

Andererseits verfügt jedes Konto über seine eigenen Informationen. Da braucht doch nix synchronisiert werden, oder?


> Die Kontos sollen Berichte erstellen können. Bericht der letzten 30 "Tage" Bericht eines Monats

Soll nun das Konto oder der zugreifende Thread den Bericht erstellen?


Was ist eine Bank? Eine Sammlung aus Konten? Eine Sammlung aus Transaktionen? ... Davon hängt die Modellierung ab :)
