### ISSUE TITLE
Logo für PM-Dungeon/PM-Lecture gesucht

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#126]
Es wird ein kleines `.png` gesucht, welches hier im Github als Logo für die PM-Dungeon-Organisation verwendet werden kann und auch für die generierten Skripte oben links als Logo verwendet werden kann. Am besten wäre eine selbst erstellte Abbildung. Beispiele: https://github.com/KI-Vorlesung oder https://github.com/Compilerbau ...

**Comment by cagix** [comment]
> Ich fände einen kleinen Helden mit Schwert oderso nicht schlecht.

Sie haben weise gewählt :) ... So, jetzt brauche ich nur noch ne handgeklöppelte Skizze, die zudem noch gut erkennbar ist ... :)

Wir müssen ja sehr mit den Lizenzen etc. aufpassen, sonst wird auf jeder popeligen Seite ein Hinweis fällig. (Teilweise geht das aber gar nicht -- also selber machen.)

**Comment by Tobias321** [comment]
> Ich fände einen kleinen Helden mit Schwert oderso nicht schlecht.

Ich bin auch für kleiner Held mit Schwert und (Dungeon-)Hintergrund!

**Comment by cagix** [comment]
Held ist gut. Legt jemand eine neue Grafik an? Quasi handgeklöppelt?

**Comment by Tobias321** [comment]
Hier der Versuch mit Paint :D 

![held1](https://user-images.githubusercontent.com/85501570/155475101-084170d9-12c2-4de3-84e6-734e70c08b62.png)

**Comment by cagix** [comment]
klasse 👍

**Comment by cagix** [comment]
@Tobias321 Du könntest bitte einen PR aufmachen und 
![`static/images/favicon.png)](https://github.com/PM-Dungeon/PM-Lecture/blob/master/static/images/favicon.png)
 und 
![`static/images/logo.png`](https://github.com/PM-Dungeon/PM-Lecture/blob/master/static/images/logo.png) mit Deinem Bild
 ersetzen. Bitte auf den File-Typ achten.

**Comment by cagix** [comment]
@Tobias321 Du könntest bitte einen PR aufmachen und [`static/images/favicon.png`](https://github.com/PM-Dungeon/PM-Lecture/blob/master/static/images/favicon.png) und [`static/images/logo.png`](https://github.com/PM-Dungeon/PM-Lecture/blob/master/static/images/logo.png) mit Deinem Bild ersetzen. Bitte auf den File-Typ achten.

**Comment by Tobias321** [comment]
@cagix Ok, mache ich. Müssen bestimmte Maße des pngs beachtet werden?

**Comment by cagix** [comment]
gute frage! muss ich mal bei dem [theme](https://mcshelby.github.io/hugo-theme-relearn/) schauen, ob die was dazu schreiben. 

bisher hatten wir was ungefähr quadratisches, das passte ganz gut. 

es sollte nach möglichkeit nur wenige kb groß sein (die alten sind ca. 10kb).

**Comment by cagix** [comment]
https://mcshelby.github.io/hugo-theme-relearn/basics/customization/#change-the-favicon sagt, dass man eigentlich nur ein `logo.png` braucht unter `static/images/`. 

eine info zum seitenverhältnis o.ä. gibt es nicht, aber ich könnte mir vorstellen, dass es günstiger ist, wenn das bild ungefähr quadratisch ist (oder sonst eher breiter als höher ist).

**Comment by cagix** [comment]
@Tobias321 ich sehe, dass du unter dem bild und rechts relativ viel rand hast. den würde ich noch reduzieren, analog zum linken und oberen rand.

**Comment by cagix** [comment]
@cagix das logo muss noch für die organisation eingerichtet werden … reopening
