### ISSUE TITLE
[QUESTION] Neues Theme?

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#127]
Aktuell verwenden wir als Theme für die Skripte das [Hugo Learn Theme](https://github.com/matcornic/hugo-theme-learn). 

Mich stören dabei vor allem drei Dinge:
1. Die Schrift ist irgendwie zu "opulent" und braucht viel zuviel Platz.
2. Beim Ausdrucken einer Seite bleibt das Menü auf der linken Seite erhalten, d.h. man hat lauter Seiten, wo nur die Hälfte mit Inhalt belegt ist.
3. Es gibt keinen automatischen Dark-Mode.
4. Das Theme entwickelt sich kaum weiter. Wobei man sich jetzt streiten kann, ob das ein Nachteil ist.

Ich habe ein Auge auf [Geekdocs](https://github.com/thegeeklab/hugo-geekdoc) geworfen. Das Theme ist unter aktiver Entwicklung und adressiert die obigen Punkte. Allerdings hat ein erster Test gezeigt, das der Umstieg vermutlich nicht ganz so einfach sein wird, da intern mit anderen Templates etc. gearbeitet wird. Im Großen und Ganzen läuft es erstmal, aber es gibt viele kleine Details (Menü muss noch eingeklappt werden, Bilder skaliert werden, die Custom CSS für TLDR und so neu eingebunden werden, **Mathe** muss von MathJax auf Katex umgestellt werden, ...).

**Update**: [Hugo Relearn Theme](https://github.com/McShelby/hugo-theme-relearn) ist ein Fork, der aktiv weiter entwickelt wird. Nach erster Sichtung ist das Ding direkt kompatibel zum alten Theme und bietet einen Dark-Mode an. Das Print-Issue (2) scheint dort aber auch zu existieren.

Alternativ könnten Dinge direkt in Github umgesetzt werden. Damit würde aus der etwas fragilen Pipeline `.md > Pandoc > .md > Hugo > .html` zumindest Hugo herausgenommen. Die Dateien würden weiterhin als Markdown im Repo gepflegt und per Workflow in ein Format übersetzt, welches Github in der Vorschau gut rendern kann und welches möglichst viele Dinge unterstützt, die wir brauchen (Text, Abbildungen, Code, Mathe, Literatur). Derzeit scheint das Markdown und Jupyter zu sein.

Frage an alle: Welches Theme/Variante findet ihr besser für die Vorlesung? Hier ein paar Screenshots von beiden Themes:

### Github direkt (Markdown vs. Jupyter)

Siehe Readme in https://github.com/KI-Vorlesung/kitest (die Links der drei "Vorlesungen").

### Hugo-Learn-Theme

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 08" src="https://user-images.githubusercontent.com/20356276/154114586-d34928b9-6d05-4522-bf75-248c21af21d3.png">

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 16" src="https://user-images.githubusercontent.com/20356276/154114627-25864434-2dd1-4ec3-97ac-9c4316372ca9.png">

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 19" src="https://user-images.githubusercontent.com/20356276/154114657-1f42dd4f-45ab-4285-98a9-8898cf4cb873.png">

### Geekdocs

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 21" src="https://user-images.githubusercontent.com/20356276/154114681-36395128-da61-4374-ac0c-c3fe31704ab5.png">

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 24" src="https://user-images.githubusercontent.com/20356276/154114738-b79d3002-f64f-44b2-a74d-9a5d95b1b9bd.png">

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 27" src="https://user-images.githubusercontent.com/20356276/154114782-e0a6113d-9df5-43e7-a835-d87a101691e8.png">

<img width="1359" alt="Screenshot 2022-02-15 at 18 12 56" src="https://user-images.githubusercontent.com/20356276/154114815-2f4b440e-d33d-41af-a3cc-2e175df46ca7.png">

---

edit: Link zu Versuchen mit Github direkt ergänzt

**Comment by cagix** [comment]
@FinnAmini @AHeinisch @CrappyAlgorithm @AMatutat @Tobias321 Sagt mal bitte jeder kurz seine Meinung dazu!

**Comment by Tobias321** [comment]
https://user-images.githubusercontent.com/20356276/154114815-2f4b440e-d33d-41af-a3cc-2e175df46ca7.png

gefällt mir am besten ((light) dark theme)

**Comment by cagix** [comment]
> https://user-images.githubusercontent.com/20356276/154114815-2f4b440e-d33d-41af-a3cc-2e175df46ca7.png
> 
> gefällt mir am besten ((light) dark theme)

@Tobias321 wenn du auf dunkle themes stehst: ich habe einen fork vom ursprünglichen theme gefunden, der auch dark-mode kann und der (nach ersten tests) direkt als ersatz genutzt werden kann:
<img width="1235" alt="Screenshot 2022-02-16 at 13 08 48" src="https://user-images.githubusercontent.com/20356276/154261861-f3e87f76-087a-487e-baec-4828d7b94e37.png">

wie findest du das im vergleich zum geekdocs?

**Comment by Tobias321** [comment]
> wie findest du das im vergleich zum geekdocs?

ich finde beides besser lesbar als im hellen theme...

**Comment by cagix** [comment]
knorke. 

ich denke, für dieses semester fehlt mir die zeit, alles auf geekdocs umzustellen, insofern wäre das relearn eine kurzfristige alternative. aber mittelfristig wäre geekdocs schon eine option. 

mal sehen, ob die anderen auch noch ne meinung haben...

**Comment by cagix** [comment]
#135 wird hugo-relearn als ersatz einführen, dann haben wir kurzfristig den dark-mode.

oh, und drucken geht jetzt auch (hatte nen bug aufgemacht).

**Comment by FinnAmini** [comment]
Ich finde auch Hugo Relearn am besten
