### ISSUE TITLE
Reihenfolge der Vorlesungen festlegen

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#182]
Um die Reihenfolge, in der wir die Aufgaben erstellen möglichst sinnig zu gestalten, wäre ein konkreter Zeitplan wichtig.

@cagix wenn du mein Held der Woche sein willst, müsstest du das bei Freitag vor dem Treffen fertig haben. Dann können wir gezielt die nächsten Tickets verteilen. 

Update: hängt von  #49 ab

**Update**: Excel im Branch `planung` (siehe PR #184)

**Comment by cagix** [comment]
@AMatutat  zeitlich wird in den ersten wochen drankommen: git, generics, junit (mit den blöcken wie im wiki). 

damit sind die tutoren jetzt erstmal drei wochen beschäftigt (aufgaben, lösungen, tests, vorgaben; konzept- und dungeon-aufgaben). danach habe ich dann auch den restlichen plan.
