### ISSUE TITLE
VL neu: Frameworks

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#191]

**Comment by AMatutat** [comment]
@cagix folgende Struktur/Inhalte hab ich mir überlegt

- [ ] Was sind Frameworks
- [ ] Abgrenzung zu Libraries
- [ ] Vor und Nachteile von Frameworks
- [ ] Ein paar Beispiel Java Frameworks (grob anreißen was die machen)

**Comment by cagix** [comment]
Klingt sinnvoll. Die ersten drei Punkte gehen vermutlich auf 1..2 Folien, die Beispiele sind das Interessante hier :)
