### ISSUE TITLE
Konzeptaufgabe: Flyweight Pattern

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#262]

**Comment by AHeinisch** [comment]
Ideen:

Code erklären, ob es Flyweight Pattern ist.
Wo der Unterschied zwischen Flyweight und Factory.

**Comment by cagix** [comment]
@AHeinisch Dieses Ticket kann zu, oder?

**Comment by AMatutat** [comment]
ich brauche noch die vorgaben im vorgabe-repo

**Comment by cagix** [comment]
och menno. der mist ist doch fertig. @AHeinisch mach doch mal bitte die pr's auf, damit es weiter geht ...
