### ISSUE TITLE
Beschreibungstext für Praktikumsseite vs. Grading (Note&Credits)

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#320]
Für die Landing-Page des Praktikums (`assignments/_index.md`) muss die Beschreibung noch angepasst werden. 

Dabei sollten kurz und knapp die Bedingungen für die Bearbeitung (jede Woche Z Punkte max., Nachbearbeitung), die Bedingungen für das Bestehen (X Punkte aus Pool Y) und das Projekt dargestellt werden.

Es gibt auch die Seite `org/grading.md`, wo auf die Prüfungsform und die Bestandteile eingegangen wird. Eventuell ist es sinnvoll, die ganzen Informationen dort unterzubringen und auf der Landing-Page des Praktikums (`assignments/_index.md`) einen Link dorthin zu machen und dann die Auflistung der Pools?

### Idee A 

In #203 die formalen Dinge (Prüfungsform, Notenspiegel, Teilleistungen, Puffer/Krankheit, ...) erklären. Hier (#320) Überblick über die Punkte/Mindestpunkte und Hinweise zum Ablauf des Praktikums.

Vorteil: Die formalen Dinge stehen zusammen, die praktischen Dinge stehen zusammen, beide Seiten werden übersichtlicher.

Nachteil: Orga-Kram wird auf eine Inhaltsseite (Praktikumslandingpage) verlagert.

### Idee B

In #203 die formalen Dinge (Prüfungsform, Notenspiegel, Teilleistungen, Puffer/Krankheit, ...) erklären. Zusätzlich unter `Ablauf Praktikum` einen Überblick über die Punkte/Mindestpunkte und Hinweise zum Ablauf des Praktikums. Hier (#320) nur die Auflistung der Pools und einen Link auf die Orga/Prüfungen.

Vorteil: Der gesamte Orga-Kram liegt jetzt unter `org/...`, hier im Praktikum sind nur noch die Inhalte.

Nachteil: Die Prüfungsseite wird recht groß und unübersichtlich. Die Informationen zum praktischen Ablauf werden vermutlich eher hier im Praktikum als unter "Note&Credits" gesucht.

siehe auch #203

--- 

Plan-Workload: 10 Punkte (Dungeon A+B+C) + 10 Punkte (Konzept)
Pro Woche max. 15 Punkte (Dungeon A+B+C)
Abgabe: über Repo (PR/MR), Vorstellung im Praktikum

Konzept: Festgelegt auf Woche, nicht nachzuarbeiten
A+B+C: Bearbeitung frei wählbar, pro Woche max. 15 Punkte erreichbar; Nachbearbeitung möglich
P: streckt sich über zwei Wochen (jede Woche 10P), in der Zeit keine Aufgaben aus A+B+C, keine Nachbearbeitung

Jeder Pool muss für sich bestanden sein: absolute Punktezahl vorgeben!
A: 28P => 14P
B: 22P => 11P
C: 30P => 15P
P: 40P => 15P
K: 100P => 50P

90P (K) + 90P (Dungeon) => 100% für Praktikumsnote (10P K + 30P Dungeon Überhang)
(50% K, 60% Dungeon für Bestehen)

60:40 Praktikum zu Klausur

Projekt:
-   Spätestens eine Woche vor Projekt: Im Praktikum Pitch mit Jonas diskutieren
    -   Konzept kann mdl. sein, dient vor allem der Machbarkeit und Aufwandsabwägung
    -   10P für inhaltliche Dinge absprechen
-   Erste Woche: Feinkonzept, Grundgerüst/Grobimplementierung
    -   10 Punkte für Feinkonzept und Grundimplementierung
-   Zweite Woche: Implementierung, Dokumentation, Lerntagebuch
    -   Inhaltliche Punkte für Umsetzung
    -   Punkte für schriftliche Ausarbeitung: **Kriterien TDB**
    -   Abzüge wie bei den Dungeon-Aufgaben sonst
=> erstes Projekt: entweder in der Woche vor dem E-Assessment oder in der Woche mit dem E-Assessment

Schema für die Aufgaben:
-   Bewertung der Inhalte: sinnvoll umgesetzt? => Punkte aus Aufgabe
    => Teilpunkte auf Aufgabenblatt
Pro Abgabe (10P Ziel, 15P max.):
-   Tests? -2P
-   Logging? -1P
-   Javadoc? -1P
-   Style? -1P
Lerntagebücher: ohne/mangelnde Qualität: keine Bewertung der Dungeon-Aufgaben
=> Vor Projekt: nur Vorhandensein und Struktur (sonst keine Bewertung; inhaltliches Feedback)
=> Im Projekt: Inhalt wird mit bewertet
Konzeptaufgaben: 10P

Tutor macht mit Studis zusammen Eintrag in die Liste (Master schreibgeschützt bzw. nur per PR)

**Comment by AMatutat** [comment]
Mein Bauchgefühl spricht für Idee A. Einfach weil ich Infos zum Ablauf des Praktikums ehr bei den Praktikums Aufgaben suchen würde.

**Comment by cagix** [comment]
Hmmm, ich muss halt unter Note&Credits eh die Punkte und so aufschlüsseln und da quasi auch was zum Praktikum sagen. Oder für den letzten Teil auf die Landingpages vom Praktikum und den Pools verlinken? Hmmm 🤔

**Comment by cagix** [comment]
@AMatutat Ich ärgere mich halt nur grad über die Vermischung aus Inhalten und Orga-Kram. Vielleicht ist es doch besser, ein Repo für die Inhalte zu haben (was dann auch hübsch gerendert wird auf die eine oder andere Art) und zusätzlich ein Semester-Repo, wo die Orga-Sachen als Markdown drin sind (und nicht extra gerendert werden) plus ein Markdown-Table mit Links in das Inhalte-Repo und plus ein (geschlossenes) Diskussionsforum und so? ... 🤔🤷

**Comment by AMatutat** [comment]
`RepoOverflowException`

Ich sehe den Vorteil der Trennung zwischen Orga und Inhalt nicht.

**Comment by cagix** [comment]
> `RepoOverflowException`
> 
> 
> 
> Ich sehe den Vorteil der Trennung zwischen Orga und Inhalt nicht. 

die inhalte ändern sich von semester zu semester nicht so sehr, der orga-kram schon. aber vielleicht ist das auch nur ein spleen von mir, da ne saubere trennung haben zu wollen 🤪
