### ISSUE TITLE
Konzeptaufgabe: Serialisierung

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#333]

**Comment by CrappyAlgorithm** [comment]
@cagix 
Man könnte eine Datenklasse vorgeben und die Studierenden dann 2 Projekte anlegen lassen.
1. Ein Objekt der Datenklasse serialisieren und in Datei speichern.
2. Datei laden, wieder in Objekt umwandeln und Ausgeben (Oder im Debugger zeigen vielleicht?)
   - Dazu könnte man dann auch noch eine Datei mit einem serialisierten Objekt zum Laden vorgeben.

Das wäre dann nur eine kleine Aufgabe, aber mehr fällt mir dazu so auch nicht ein.

**Comment by cagix** [comment]
Finde ich gut, und das wäre auch dem Umfang dieser Konzept-Aufgaben angemessen (zumal ja sowieso noch weitere Aufgaben hier zu einem Blatt gruppiert werden).

Wenn man ein serialisiertes Objekt vorgibt, muss man dann aber auch gleich wieder Schnittstellen und so mit vorgeben. Ich bin nicht sicher, ob sich das lohnt.

**Comment by cagix** [comment]
ja, sehe ich auch so. machbar, aber (unnötig) hakelig ...

**Comment by CrappyAlgorithm** [comment]
Ja, da muss ich euch zustimmen. Genau die Bedenken hatte ich auch schon.
