### ISSUE TITLE
Konzept-Blätter: Einbinden der Aufgabenschnipsel, Ordner-Strukturen und Workflows im Lecture-Repo

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#334]
https://github.com/PM-Dungeon/PM-Lecture/wiki/Workflow-Erstellung-Konzeptaufgaben

---

### Idee
Die Konzept-Blätter liegen unter `markdown/assignments/pool_k/sheetXX/`. Diese Blätter sind über die `data/schedule.yaml` mit festen Abgabefristen versehen. 

Um bei der Zuordnung der konkreten Aufgaben zu den Blättern/Abgaben flexibler zu sein, wird unter `markdown/assignments/pool_k/` ein weiterer Unterordner `tasks/` angelegt. Dort werden die Aufgaben als Markdown-Schnipsel gesammelt.

### Workflow Tutoren

Die Tutoren haben für ihre Aufgaben in ihren Repos eine Aufgabenstellung (Markdown), eine Vorgabe und eine Musterlösung erstellt.

Für die Übertragung der Aufgabe in das Lecture-Repo erstellt jeder Tutor einen Branch vom `master` aus plus einen Pull-Request in den `master` direkt hier im Lecture-Repo. **Konvention**: Wenn das bearbeitete Ticket "Konzeptaufgabe: JUnit Basics" heisst, dann heisst der neue Branch "`junit_basics`" und entsprechend der PR "Add: Konzeptaufgabe JUnit Basics". (Leerzeichen werden durch einen Unterstrich ersetzt, Kommas und der Text "Konzeptaufgabe: " weggelassen und alle Zeichen auf Kleinschreibung umgestellt.)

In diesem PR stellen die Tutoren ihre Aufgabe als Markdowndatei im Ordner `markdown/assignments/pool_k/tasks/` zum Mergen bereit. Die Namenskonvention ist dabei wieder "`junit_basics.md`", wenn das bearbeitete Ticket "Konzeptaufgabe: JUnit Basics" ist. 

Der PR wird von den Erstellern zum Review und zum weiteren Bearbeiten(!) an @cagix und @AMatutat zugewiesen.

### Aufbau der Markdown-Textschnipsel

Die Aufgabenschnipsel haben folgenden Aufbau:

```markdown
### Titel (aber ohne "Aufgabe" o.ä.)

Text Text Text Code ...

```

Also ein Header Stufe 3, eine Leerzeile, der Aufgabentext (bei 80 oder 90 Zeichen umgebrochen) und ein Zeilenumbruch am Dateiende.

### Workflow Core-Team

Das Core-Team kann die Aufgabenschnipsel in den Konzeptaufgaben so einbinden:

```markdown
---
type: assignment
title: "Wuppie"
author: "Andre Matutat (FH Bielefeld)"
points:
weight: 1
hidden: true
---


## Aufgabe 1

`[Wuppie]({{<ref "/assignments/pool_k/tasks/wuppie" >}})`{=markdown}

## Aufgabe 2

`[Wuppie]({{<ref "/assignments/pool_k/tasks/wuppie" >}})`{=markdown}

## Aufgabe 3

`[Wuppie]({{<ref "/assignments/pool_k/tasks/wuppie" >}})`{=markdown}
```

Damit werden entsprechende Links auf die Schnipsel erstellt. 

**Anmerkung**: Eigentlich war geplant, die Einbindung als echtes Include mittels des `include`- Shortcodes zu machen: `{{% include "assignments/pool_k/tasks/fluppie.md" "false" %}}`. Da Pandoc aber mit der (für sämtliche anderen Markdowndateien wichtigen) Option `--self-contained` aufgerufen wird, schreibt es einen (leeren) YAML-Header in die Schnipsel. Da diese dann direkt in die Aufgaben-Seite kopiert werden, sorgt dies für zwei horizontale Striche. Man müsste das Makefile so ergänzen, dass die Aufgabenschnipsel nicht mit Pandoc bearbeitet werden, was durch die Komplexität des Makefiles aber etwas Zeit braucht.

**Comment by AMatutat** [comment]
eigentlich was für das wiki, oder?

**Comment by cagix** [comment]
> eigentlich was für das wiki, oder?

ja, übertrage ich morgen

**Comment by cagix** [comment]
@PM-Dungeon/core @PM-Dungeon/codemonkeys @PM-Dungeon/quizzes @PM-Dungeon/teachingassistents 

Ich habe den Workflow zum Übertragen der Aufgabenschnipsel in VL-Repo (PM-Lecture), der Vorgaben ins Vorgabe-Repo (Assignment-Stubs) und der Musterlösung ins Musterlöungs-Repo (Homework-Solutions und Dungeon-Solutions) ins Wiki übertragen (siehe https://github.com/PM-Dungeon/PM-Lecture/wiki/Workflow-Erstellung-Konzeptaufgaben).

**Comment by cagix** [comment]
@PM-Dungeon/codemonkeys @PM-Dungeon/teachingassistents Der Workflow funktioniert zwar, ist aber **viel** zu komplex.

Vorschlag: Wir lassen die individuellen Repos weg (und löschen sie auch direkt). Die Aufgabe plus Vorgabe plus Musterlösung wird in https://github.com/PM-Dungeon/Homework-Solutions (private) in Themenbranches erstellt und gereviewt. Nach dem Merge wird die Aufgabe per PR ins Lecture-Repo übertragen und die Vorgaben analog per PR ins Vorgabe-Repo. Dort dann jeweils noch ein kurzes Review zum Abgleich (Vollständigkeit, Korrektheit), aber keine Entwicklung mehr.

**Comment by AHeinisch** [comment]
@cagix, das klingt für mich persönlich besser. Theoretisch war für mich am Anfang nicht klar das in Homework-Solutions alles enthalten sein soll also Aufgabe/Vorgabe/Lösung. Ich wäre für diesen Vorschlag, dadurch entfällt zumindest 1 schritt.

**Comment by cagix** [comment]
@PM-Dungeon/codrs @PM-Dungeon/core @PM-Dungeon/teachingassistents siehe https://github.com/PM-Dungeon/PM-Lecture/wiki/Workflow-Erstellung-Konzeptaufgaben#workflow-tutoren-erstellung-der-aufgaben
