### ISSUE TITLE
Aufgaben: Pools sinnvoll benennen

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#347]
Auf den Landing-Pages der Pools sinnvolle Benennungen der Pools eintragen: 

1.  Pool "Dungeon" mit max. 110 Punkten (mind. 50 Punkte zum Bestehen)
    *   Gruppe A "Basics" (38 P)
    *   Gruppe B "Monster und Kampf" (32 P)
    *   Gruppe C "Items, Aufbewahrung und Handel" (40 P)
2.  Pool "Konzept" mit max. 100 Punkten (mind. 50 Punkte zum Bestehen)

@AMatutat Passen die neuen Punkte? Ich habe auf jeden Sub-Pool die 10P für die freie Aufgabe draufaddiert.

(siehe https://github.com/PM-Dungeon/PM-Lecture/pull/317)

**Comment by AMatutat** [comment]
sieht richtig aus,
