### ISSUE TITLE
André hat immer noch keinen vernünftigen Markdown-Editor

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#361]
In den Aufgaben, die @AMatutat bereitgestellt hat, taucht seltsames Verhalten auf:
- Markdown: Manchmal lassen sich Wörter einzeln selektieren, manchmal nur als Gruppe

<img width="928" alt="Screenshot 2022-03-30 at 18 44 55" src="https://user-images.githubusercontent.com/20356276/160891092-e056a692-080d-401f-9e09-9f992109a28b.png">

<img width="928" alt="Screenshot 2022-03-30 at 18 45 05" src="https://user-images.githubusercontent.com/20356276/160891118-6d530b68-b952-4b68-a5bf-94ee3684d829.png">

- Web: Manche Sätze werden normal umgebrochen, bei manchen aber mitten im Wort(?!) oder mitten in der Zeile(?!)

<img width="958" alt="Screenshot 2022-03-30 at 18 45 57" src="https://user-images.githubusercontent.com/20356276/160891148-cc56b66f-fb5b-45b7-95d4-ff72e72a95e7.png">

Der Markdown-Code sieht zunächst aber vernünftig aus.

Vermutung: Da sind unterschiedliche Leerzeichen am Start?!

- [ ] Rausfinden, was zum Geier da los ist
- [ ] Suchen&Ersetzen in VSCode im Ordner-Modus

**Comment by AMatutat** [comment]
ich nutz doch schon vscode :/

**Comment by cagix** [comment]
🤣 vielleicht ein windows-problem? oder irgendwas mit copy&paste?

**Comment by AMatutat** [comment]
> vielleicht ein windows-problem? oder irgendwas mit copy&paste?

das könnte natürlich beides sein. Ich guck mal ob ich VsCode irgendwie rausfinden kann, welchen Standard das Ding nutzt.

**Comment by cagix** [comment]
> > vielleicht ein windows-problem? oder irgendwas mit copy&paste?
> 
> das könnte natürlich beides sein. Ich guck mal ob ich VsCode irgendwie rausfinden kann, welchen Standard das Ding nutzt.
> 
> Edit: ist UTF8 hmm

ich bin schon dabei. fass das bitte nicht an.

**Comment by AMatutat** [comment]
ich fasse nix an, ich gucke nur 👀

**Comment by cagix** [comment]
Es war ein "` `" ... :)

Und ich hatte mich noch gewundert, warum im Github in der Review-Ansicht so komische Umbrüche drin waren. 

Lustigerweise hatte ich auch exakt ein so ein Ding drin in den Ressourcen: Da hab ich nen String aus einer Webseite kopiert (Name von irgendwas), und da kam das mit rein. Vermutlich war das bei Dir auch so, und vielleicht hat VSC dann gesagt, na gut, wenn er das so benutzt, mach ich das auch immer?

**Comment by cagix** [comment]
lustigerweise ist pandoc jetzt bei "make web" auch deutlich schneller

**Comment by AMatutat** [comment]
> Es war ein " " ... :)

Hmm, interessant. 

> Und ich hatte mich noch gewundert, warum im Github in der Review-Ansicht so komische Umbrüche drin waren.

Ah da kommt das her. Ich hab schon gedacht mit GitHub gehts jetzt ganz bergab,
