### ISSUE TITLE
Musterlösung für die Konzept-Aufgaben im Wiki anpassen? [QUESTION] 

### ISSUE THREAD

**Issue by jedi101** [PM-Dungeon/PM-Lecture#369]
Damit die Aufgaben im `Homework-Solutions` repo einheitlich eingepflegt werden, könnten wir dann diesen Satz im Wiki unter der
Rubrik: [Musterlösung für die Konzept-Aufgaben](https://github.com/PM-Dungeon/PM-Lecture/wiki/Workflow-Erstellung-Konzeptaufgaben#musterl%C3%B6sung-f%C3%BCr-die-konzept-aufgaben)

> Struktur: aufgabe/aufgabe.md, aufgabe/vorgabe/, aufgabe/loesung/, d.h. bezogen auf das Beispiel wäre dies junit_basics/junit_basics.md, junit_basics/vorgabe/, junit_basics/loesung/.

ändern zu:

Struktur: aufgabe/aufgabe.md, aufgabe/vorgabe/, aufgabe/loesung/.

**Comment by cagix** [comment]
??? Wo ist der Unterschied zum aktuellen Text?

**Comment by jedi101** [comment]
Den Teil: 

..."d.h. bezogen auf das Beispiel wäre dies junit_basics/junit_basics.md, junit_basics/vorgabe/, junit_basics/loesung/."

einfach weglassen - Ist aber nicht so wichtig. Wir wissen ja eigentlich nun alle wie es funktioniet. 

Frage kann eigentlich auch zu.

**Comment by cagix** [comment]
> Den hinteren Teil:
> 
> ..."d.h. bezogen auf das Beispiel wäre dies junit_basics/junit_basics.md, junit_basics/vorgabe/, junit_basics/loesung/."
> 
> des Satzes:
> 
> "Struktur: aufgabe/aufgabe.md, aufgabe/vorgabe/, aufgabe/loesung/, d.h. bezogen auf das Beispiel wäre dies junit_basics/junit_basics.md, junit_basics/vorgabe/, junit_basics/loesung/."
> 
> einfach weglassen.
>

hmmm, dann geben aber alle nur noch "aufgabe/" ab :) ...

**Comment by cagix** [comment]
@jedi101 hab mal was geschrieben und aus `junit_basics/junit_basics.md` ein `junit_basics/aufgabe.md` gemacht, da das ja der akzeptierte name zu sein scheint für das musterlösungsrepo ... schau mal, ob das jetzt besser ist?
