### ISSUE TITLE
Fahrplan: Dungeon-Starter-Aufgabe verlinken

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#372]

**Comment by cagix** [comment]
@AMatutat Das könnte ich hinbekommen, müsste aber die Bemerkung als "Blatt" eintragen. Das würde ich dann gern auch bei den anderen Blättern einbauen. 

Aber: Wir haben keine eigene Landing-Page nur für Dungeon-Aufgaben. Sollte ich ein Refactoring machen und unter "assignments/" zwei neue Unterordner "dungeon/" und "concept/" erstellen und die drei Dungeon-Gruppen/-Pools dort hinein verschieben? 

Dann könnte man für jede Woche auf den Dungeon-Ordner verlinken analog zu den Konzeptblättern.

Die Frage ist halt, wo ich über alle diese Ordner eingebaut/referenziert habe. Aber das sollte sich mit einer Sucher herausfinden lassen.

Was denkst Du?

**Comment by AMatutat** [comment]
> Aber: Wir haben keine eigene Landing-Page nur für Dungeon-Aufgaben. Sollte ich ein Refactoring machen und unter "assignments/" zwei neue Unterordner "dungeon/" und "concept/" erstellen und die drei Dungeon-Gruppen/-Pools dort hinein verschieben?

Das klingt sinnvoll und ehrlichgesagt dachte ich, wir hätten eine.

**Comment by cagix** [comment]
> > Aber: Wir haben keine eigene Landing-Page nur für Dungeon-Aufgaben. Sollte ich ein Refactoring machen und unter "assignments/" zwei neue Unterordner "dungeon/" und "concept/" erstellen und die drei Dungeon-Gruppen/-Pools dort hinein verschieben?
> 
> Das klingt sinnvoll und ehrlichgesagt dachte ich, wir hätten eine.

wir hatten eine für das gesamte praktikum und dann nochmal für jeden teil-pool. aber so haben wir jetzt zwei neue unterordner `pool_dungeon/` und `pool_concept/` und alles ist schick :)
