### ISSUE TITLE
Einheitliche Ordnerstrukturen in Vorgaben

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#387]
Mir ist aufgefallen, dass die Ordnerstrukturen im Vorgabe-Repo sehr unterschiedlich ausfallen: Das reicht von `<thema>/src/...` bis hin zu `<thema>/src/main/java/...`.

Sollte das einheitlich sein? Und wenn ja, welche Struktur wollen wir dort einsetzen? Mir erscheint die Maven-/Gradle-Struktur hier etwas arg als Overkill?

**Comment by jedi101** [comment]
Bin auf jeden Fall für einheitlich. Wie immer das dann auch aussehen mag. Ich fände: "<thema>/src/..." gut.

**Comment by Tobias321** [comment]
> Mir erscheint die Maven-/Gradle-Struktur hier etwas arg als Overkill?

Moin, das hat (im Vorgabe-Repo) aber den Vorteil, dass man es clonen kann und danach quasi direkt ausführen kann. Nachteil: Es ist etwas aufwändiger und legt die Struktur auf Maven/Gradle fest...

**Comment by Tobias321** [comment]
> Bin auf jeden Fall für einheitlich. Wie immer das dann auch aussehen mag. Ich fände: '< thema>/src/...' gut.

Ich bin auch immer für einheitliche Strukturen... Maven möchte (in der Regel) nur `src/` haben und Gradle nur `src/main/java/` - wir sollten uns auf eins festlegen oder auf einen "Trade-off", mMn.

**Comment by Tobias321** [comment]
> > Bin auf jeden Fall für einheitlich. Wie immer das dann auch aussehen mag. Ich fände: '< thema>/src/...' gut.
> 
> Ich bin auch immer für einheitliche Strukturen... Maven möchte (in der Regel) nur `src/` haben und Gradle nur `src/main/java/` - wir sollten uns auf eins festlegen oder auf einen "Trade-off", mMn.

Sorry, ich hab das gerade verwechselt, mvn möchte (auch?) `src/main/java/` haben: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by cagix** [comment]
ja, maven hat den quatsch eingeführt und gradle hat es übernommen.

aber: zumindest in gradle kann man das einfach konfigurieren, so dass man auch mit nem simplen `src/` direkt als gradle-projekt durchkommt ...

**Comment by Tobias321** [comment]
> so dass man auch mit nem simplen `src/` direkt als gradle-projekt durchkommt

Aber dann ginge doch auch nur `<thema>/...` - es wird dann nur unübersichtlich, falls auch Testklassen dabei sind...

**Comment by cagix** [comment]
> > so dass man auch mit nem simplen `src/` direkt als gradle-projekt durchkommt
> 
> Aber dann ginge doch auch nur `<thema>/...` - es wird dann nur unübersichtlich, falls auch Testklassen dabei sind...

ja, du musst in jedem `<thema>/` ein eigenes gradle-file haben. und ja, `test/` geht genauso wie `src/` zu konfigurieren. und wer will, könnte sich on top auch noch ein gesamt-gradle reinwerfen. 

geht alles.

**Comment by Tobias321** [comment]
> ja, du musst in jedem `<thema>/` ein eigenes gradle-file haben

Hm, ich hatte das Buildfile in Assignment-Stubs jetzt nicht mit dabei, sollte man das mit hochladen oder ist das ein Teil der Aufgaben der Studis, ein Buildfile anzulegen?

**Comment by Tobias321** [comment]
> > > Bin auf jeden Fall für einheitlich. Wie immer das dann auch aussehen mag. Ich fände: '< thema>/src/...' gut.
> > 
> > 
> > Ich bin auch immer für einheitliche Strukturen... Maven möchte (in der Regel) nur `src/` haben und Gradle nur `src/main/java/` - wir sollten uns auf eins festlegen oder auf einen "Trade-off", mMn.
> 
> Sorry, ich hab das gerade verwechselt, mvn möchte (auch?) `src/main/java/` haben: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

Ich wäre für die offizielle Maven-Struktur, aber ohne Vorgabe das Maven-/Gradle-Buildscripts.

**Comment by jedi101** [comment]
Fände ich auch gut, dann bräuchte ich aber mal ein Beispiel buildscript wo das richtig konfiguriert ist. Hatte bislang leider noch nicht die Zeit das bei mit mit der gewünschten Ordnerstruktur zu versehen, so das es auch ausführbar ist. Nach drei Stunden try and error mit Gradle hatte ich mich dann doch dazu entschieden das anders (einfacher) zu lösen.

**Comment by Tobias321** [comment]
> > dann bräuchte ich aber mal ein Beispiel buildscript wo das richtig konfiguriert ist.
> 
> Hab mal ein Beispiel für Gradle in "Tobias/Beispiel-Gradle/" hochgeladen.

es wäre allerdings vielleicht einfacher, wenn du mit IntelliJ selbst ein neues Gradle-Projekt anlegen würdest.

**Comment by cagix** [comment]
ohne IJ kriegt ihr nix mehr hin, oder? ;)

**Comment by cagix** [comment]
ich finde die maven-strukturen absoluten overkill für diese mini-geschichten. aber dann sei es so.

**Comment by Tobias321** [comment]
> ohne IJ kriegt ihr nix mehr hin, oder? ;)

Es geht auch ohne IDE, ist aber ggf. komplizierter.:)

https://docs.gradle.org/current/samples/sample_building_java_applications.html

**Comment by Tobias321** [comment]
> ich finde die maven-strukturen absoluten overkill für diese mini-geschichten. aber dann sei es so.

ich eigentlich auch... hm, vielleicht haben die anderen auch eine Meinung dazu.

**Comment by AHeinisch** [comment]
> ich eigentlich auch... hm, vielleicht haben die anderen auch eine Meinung dazu.

Und was ist, wenn meine Meinung durch eure Diskussion bereits von ich wäre für die einfache Struktur zu ich bin mir bei beiden nicht sicher. Also für die Studis wäre die Struktur von Maven/Gradle wahrscheinlich nicht so hilfreich, zumindest die ersten 3 Wochen. Für die Tutoren würde es beim Kontrollieren, ob es kompiliert und die möglichen Tests laufen. 
Aus der Sicht von übersichtliches Repo wäre ich dagegen. Wir bauen ganz viele Ordner auf, welche im end hinein nur hereinkommen, weil Gradle/Maven es benötigt.

Glaube aber ich wäre hier mehr auf der Seite, wenn es den Tutoren bei der Abnahme hilft, dann sollten wir es vielleicht auch machen. 

Ist dann aber nicht auch wieder die Konzeptaufgabe Gradle etwas einfach, wenn bereits Lösungen dafür in anderen Ordnern liegen?

**Comment by Tobias321** [comment]
Ok, dann nur `task/src/...` und ggf. `task/test/...`.

**Comment by cagix** [comment]
find ich gut. so einfach wie möglich. und gradle ist ja bald dran, dann können die studis sich die gradle-files ja selbst basteln.

**Comment by cagix** [comment]
habs im Wiki eingetragen: https://github.com/PM-Dungeon/PM-Lecture/wiki/Workflow-Erstellung-Konzeptaufgaben#vorgaben-für-die-konzept-aufgaben
