### ISSUE TITLE
[FEATURE] Dungeon-Start: Hinweis auf Lerntagebuch

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#408]
Auf dem Dungeon-Startblatt einen Hinweis auf das Lerntagebuch unterbringen?

**Comment by cagix** [comment]
@AMatutat Macht das Sinn? Oder ist das Overkill/Helikopter-Betreuung?

**Comment by AMatutat** [comment]
Hmm schwierig.
Für diesen Run ist es zu spät.
Aber ja, es sollte nochmal eine Notiz + Link zu genaueren Infos eingefügt werden
