### ISSUE TITLE
[FEATURE] Blatt01: Hinweise ergänzen

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#409]
- [x] Git Basics (11): Aufschreiben nicht nötig, aber Demonstration im Praktikum
- [x] Punkte für Teilaufgaben runterbrechen

**Comment by cagix** [comment]
@AMatutat Macht das Sinn? Oder ist das Overkill/Helikopter-Betreuung?

**Comment by AMatutat** [comment]
Halte ich für Overkill
