### ISSUE TITLE
[FEATURE] Blatt 02: Hinweise auf Javadoc und Logging

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#410]
Für Blatt02 wurde bereits Javadoc und Logging besprochen, d.h. das ist jetzt immer einzusetzen. Entsprechende(n) Hinweis/Erinnerung auf das Blatt?

**Comment by cagix** [comment]
@AMatutat Macht das Sinn? Oder ist das Overkill/Helikopter-Betreuung?

**Comment by AMatutat** [comment]
> Macht das Sinn? Oder ist das Overkill/Helikopter-Betreuung?

Schließt das eine das andere aus? Besser eine Notiz hinzufügen.
