### ISSUE TITLE
[BUG] Dungeon Pool A 36 punkte anstelle von 38

### ISSUE THREAD

**Issue by AHeinisch** [PM-Dungeon/PM-Lecture#423]
Im Pool A gibt es nur Aufgaben für maximal 36 Punkten anstelle von den fürs Praktikum Gruppe A angegebenen 38 Punkten. 

Hier könnte entweder eine Aufgabe fehlen oder es wurde sich verrechnet.

Pool A:
- Dungeon-Start 10
- Fähigkeiten 3
- Fallen 1
- Inventar (text basiert) 3
- Crafting 3
- Charakterklassen 3
- Speichern und Laden 3
- Freie Aufgabe 10

**Comment by AMatutat** [comment]
Hab das ganze mal mit meiner Excel-Tabelle abgeglichen:
Crafting sollte 5-Punkte geben.

**Comment by cagix** [comment]
@AHeinisch @AMatutat Fix ist unterwegs in #424 ... bitte ein schnelles Review, dann ist das auch weg :)
