### ISSUE TITLE
Schedule: Thema Enum vorziehen?

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#430]
In den aktuellen Aufgaben kann man scheinbar immer wieder Enums ganz gut gebrauchen. Das Thema ist in der VL allerdings erst sehr spät eingeplant, zudem ist nicht klar, ob das in OOP vielleicht doch ansatzweise besprochen wurde. 

Sollen wir Enums vorziehen? Wir könnten das für KW19 (W7) einplanen und dafür Collections später machen?

Gedanken?

**Comment by Tobias321** [comment]
Das finde ich für die Pattern-Aufgaben ganz nett. Vielleicht könnte man das Thema auch aufteilen in Enum Basiscs und Enum Advanced (ordinal, Enums with attributes, usw.), wobei Advanced später dran kommt.

**Comment by AMatutat** [comment]
@cagix was machst du denn Inhaltlich in Collections?

**Comment by cagix** [comment]
> @cagix was machst du denn Inhaltlich in Collections? 

tja ... tbh, ich hab noch keinen plan :/

**Comment by AMatutat** [comment]
> tja ... tbh, ich hab noch keinen plan :/

dann kann ich auch nichts vermissen. :D Dann gibts ein "ok" von mir.

**Comment by cagix** [comment]
@FinnAmini @jedi101 Ich habe Enums und Collections vertauscht. Die Label an den Quizzes und Konzeptaufgaben sollten aktualisiert sein. 

Bitte bei der Zeitplanung beachten! Enums ist jetzt nächste Woche fällig (für uns).
