### ISSUE TITLE
Orga Praktikum: Verbesserung der Abnahmezeiten

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#446]
Die Abgabeslots (30') sind zu kurz.

1. Slots auf 45 Minuten erweitern: Mittlerer Slot je 4 Teams parallel, ILIAS/Etherpads nachziehen, Studis informieren (Timeline/Mail) (@jposselt)
2. @timonBusch wechselt in den mittleren Slot, @jedi101 unterstützt am Freitag 09:45 - 10:30 und 10:45 - 11:30 (hybrid)
3. Konzeptaufgaben abspecken: Planung (@AMatutat/@cagix)
4. Übrige Konzeptaufgaben für Sprechstunde/Tutorium (@cagix, @timonBusch und @tkohlmeier98)
5. Planung Deploy-to-Abgabe (@AMatutat/@cagix)

**Comment by jedi101** [comment]
@cagix - Bin dann Freitags immer von 09:45 bis 10:30 und von 10:45 bis 11:30 mit bei der Abgabe. (Im Kalender notiert)

**Comment by cagix** [comment]
> @cagix - Bin dann Freitags immer von 09:45 bis 10:30 und von 10:45 bis 11:30 mit bei der Abgabe. (Im Kalender notiert)

danke dir 🙏👍

**Comment by AMatutat** [comment]
@cagix ich habe mal alle Aufgaben/Themen die ich ehr im Tutorium sehe mit einem Label "tutorium" versehen. Schau dir das bei Zeiten mal an. Das zweite JUnit Blatt habe ich in Sheet09 geplant.
