### ISSUE TITLE
Orga: Studi-Hilfe im Dungeon

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#451]
Studis können Punkte verdienen, wenn sie Issues im Dungeon-Code beheben. 

In die Orga aufnehmen. Alternativ neue Dungeon-Aufgaben?

**Comment by cagix** [comment]
Finde ich gut. Mach mal nen Formulierungsvorschlag für einen kurzen Absatz. Den könnte ich dann im `grading.md` an passender Stelle mit ner eigenen Überschrift einbauen.

Alternativ könnten wir aber auch ne entsprechende Dungeon-Aufgabe definieren :) ... Das wäre fast noch konsistenter.

**Comment by cagix** [comment]
Den PR https://github.com/PM-Dungeon/core/pull/249 dürfen wir dann nicht vergessen :)

**Comment by AMatutat** [comment]
> Alternativ könnten wir aber auch ne entsprechende Dungeon-Aufgabe definieren :) ... Das wäre fast noch konsistenter.

Hmm, würde aber auch ein paar implikationen mit sich ziehen
- muss einem Pool zugeordnet werden
- teil des 15P Limit
-  wir müssten eine feste Punktzahl dran schreiben
- wäre eine einmalige Aufgabe, kein Repeat möglich.

Da gefällt mir ein abschnitt in der Orga besser.

**Comment by AMatutat** [comment]
@cagix 
> Sie können aktiv dabei helfen das Dungeon-Framework weiterzuentwickeln und sich so Bonus-Punkte für das Praktikum verdienen. 
Sie können entweder Fehler beheben bzw. Features implementieren, die Sie gerne im Dungeon sehen würden oder ein bereits bestehendes Issue mit dem Label „help wanted“ bearbeiten. 
Bei der Bepunktung betrachten wir nicht nur den Fix/Code selbst sondern auch Ihren Umgang mit Git und die Qualität der Kommunikation innerhalb von GitHub (Issue-Beschreibungen, PR-Beschreibungen etc.) sowie den Umfang des Problems. Für einen PR können Sie bis zu 5 Bonus-Punkte erhalten. Es lohnt sich also, aktiv beim Fixen von Bugs mitzuhelfen.
Weitere Informationen darüber, wie Sie am Framework mitarbeiten können, finden Sie in der [Core-CONTRIBUTING.md](https://github.com/PM-Dungeon/core/blob/master/CONTRIBUTING.md)

**Comment by cagix** [comment]
> > Alternativ könnten wir aber auch ne entsprechende Dungeon-Aufgabe definieren :) ... Das wäre fast noch konsistenter.
> 
> Hmm, würde aber auch ein paar implikationen mit sich ziehen
> 
> * muss einem Pool zugeordnet werden
> * teil des 15P Limit
> * wir müssten eine feste Punktzahl dran schreiben
> * wäre eine einmalige Aufgabe, kein Repeat möglich
> 
> Da gefällt mir ein abschnitt in der Orga besser.

ja, das sind gute argumente. also orga.

**Comment by AMatutat** [comment]
@cagix wo genau willst du das denn stehen haben? Dann kann ich einen PR machen

**Comment by cagix** [comment]
> > Sie können aktiv dabei helfen, das Dungeon-Framework weiterzuentwickeln und sich so Bonus-Punkte für das Praktikum verdienen.
> >
> > Sie können entweder Fehler beheben bzw. Features implementieren, die Sie gerne im Dungeon sehen würden oder ein bereits bestehendes Issue mit dem Label "help wanted" bearbeiten.
> >
> > Bei der Bepunktung betrachten wir nicht nur den Fix/Code selbst, sondern auch Ihren Umgang mit Git und die Qualität der Kommunikation innerhalb von GitHub (Issue-Beschreibungen, PR-Beschreibungen etc.) sowie den Umfang des Problems. Für einen akzeptierten PR können Sie bis zu 5 Bonus-Punkte erhalten. Es lohnt sich also, aktiv beim Gestalten des Frameworks mitzuhelfen.
> > Weitere Informationen darüber, wie Sie am Framework mitarbeiten können, finden Sie in der [Core-CONTRIBUTING.md](https://github.com/PM-Dungeon/core/blob/master/CONTRIBUTING.md).

ein paar typos ...

**Comment by cagix** [comment]
> @cagix wo genau willst du das denn stehen haben? Dann kann ich einen PR machen

--- 

`markdown/org/grading.md`.

unter `### 1. Praktische Teilleistung` könnte noch ein kurzer Satz mit Verweis auf weiter unten kommen. 

hinter den abschnitt `### Verspätete Abgaben, Krankheit` könnte ich mir dann einen neuen abschnitt mit dem text von oben vorstellen.

---

vielleicht sollte auch in `markdown/assignments/_index.md` nochmal ein kurzer Text dazu kommen. leider haben wir die informationen ja im moment in diesen beiden dokumenten gedoppelt, d.h. das sollten wir mit dieser info dann auch tun.

---

und der text sollte in die timeline im ilias.

**Comment by AMatutat** [comment]
Timeline Eintrag ist gesendet

**Comment by cagix** [comment]
> Timeline Eintrag ist gesendet

das timing ist nicht optimal, wir hätten erst die neue webseite oben haben sollen. aber egal, das wird sicher keine sofort jetzt lesen :)

danke fürs posten!

**Comment by AMatutat** [comment]
> das timing ist nicht optimal, wir hätten erst die neue webseite oben haben sollen. aber egal, das wird sicher keine sofort jetzt lesen :)

haben wahr.

**Comment by AMatutat** [comment]
@cagix für den bereits absolvierten PR würde ich 5Punkte geben. Der war sowohl gut ausgeführt als auch gut kommuniziert.

**Comment by cagix** [comment]
> @cagix für den bereits absolvierten PR würde ich 5Punkte geben. Der war sowohl gut ausgeführt als auch gut kommuniziert.

ja mach. trägst du das im pr ein (damit die ne rückmeldung kriegen)? 

wo tragen wir das im ilias ein? so richtig haben wir da gar kein system. ich werde mal ne aufgabe "bonus" hinten anfügen. trägst du dann für die studis die punkte dort ein?

**Comment by cagix** [comment]
> @cagix für den bereits absolvierten PR würde ich 5Punkte geben. Der war sowohl gut ausgeführt als auch gut kommuniziert.

@AMatutat 

ja mach. trägst du das im pr ein (damit die ne rückmeldung kriegen)? 

wo tragen wir das im ilias ein? so richtig haben wir da gar kein system. ich werde mal ne aufgabe "bonus" hinten anfügen. trägst du dann für die studis die punkte dort ein?

**Comment by AMatutat** [comment]
mach ich

**Comment by AMatutat** [comment]
@cagix quizfrage: Kriegt die gesamte Gruppe die Punkte oder nur die, die im PR was gemacht haben? Wäre eigentlich fairer, aber ich sehe schon schräge Diskussionen kommen. Pairprogramming undso

**Comment by cagix** [comment]
> @cagix quizfrage: Kriegt die gesamte Gruppe die Punkte oder nur die, die im PR was gemacht haben? Wäre eigentlich fairer, aber ich sehe schon schräge Diskussionen kommen. Pairprogramming undso 

es wird am ende realistisch gesehen darauf hinauslaufen, dass alle drei die punkte bekommen.

aber du wirst vermutlich sowieso im pr fragen müssen, wo genau du die punkte eintragen sollst (fh-user != ilias-user). da kannst du ja fragen, wer da noch mit von der partie war. und die kriegen dann die bonuspunkte ...
