### ISSUE TITLE
Konzeptaufgabe: Exception

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#463]
Ergänzen Sie den vorgegebenen Code um Exception-Handling.
Erstellen Sie eine eigene checked und eine eigene unchecked Exception.
Die unchecked Exception soll geworfen werden, wenn ??
Die checked Exception soll geworfen werden, wenn ??
Achten Sie darauf, die Exceptions an der entsprechenden Stelle zu behandeln.

Begründen Sie, warum Sie welche Exception werfen und wo Sie diese fangen. 

Vorgaben: 
tbd

**Comment by AMatutat** [comment]
@cagix Was hältst du von einer "Clean-Code" Aufgabe zum üben (ist jetzt nicht unbedingt auf diese Aufgabe bezogen, passt aber auch dazu)?
Wir geben eine größere (und dreckige) Codebasis vor und die Studis müssen dann Anti-Pattern erkennen und beheben, Exceptions einbauen, Optional einbauen etc.  

Grade für das Tutorium wäre das ja super, dort kann man dann zusammen über den Code und mögliche Verbesserungen diskutieren etc.

**Comment by cagix** [comment]
klingt gut!

**Comment by AMatutat** [comment]
Ich hab keinen kreativen Einfall für eine reine Exception Übungsaufgabe. 
Wir könnten damit natürlich etwas in die theoretische Ecke gehen:

"Erläutern Sie den unterschied zwischen checked und unchecked Exceptions. Veranschaulichen Sie Ihre Antwort mit einem Demo-Programm. Schreiben Sie dafür eine eigene checked und eine eigene unchecked Exception."

Die Aufgabe ist eh fürs Tutorium gedacht.... 

Aber to be fair: Eigentlich ist das auch nur eine Aufgabe, um eine Aufgabe zu haben. Eine richtige Existenzberechtigung hat die nicht.

**Comment by cagix** [comment]
naja, es wäre schön, ein gerüst zu haben, über das im tutorium diskutiert werden kann und was man ggf. mit inhalten füllt.

- was fange/bearbeite ich wo (an welcher stelle)?
- werfe ich eine checked oder unchecked?
- wie schreibe ich die try/catch: besser einzelne try/catch um jede anweisung vs. die logik in einem try/catch ...
- wie geht finally und try-with-resources

dazu eine aufgabe, die nicht so extrem an den haaren herbeigezogen wirkt, wo man das diskutieren und schrittweise umsetzen kann ...

**Comment by AMatutat** [comment]
Ich könnte daraus vier kleine "Rätsel" basteln.
Code Vorgeben, anpassen/erklären lassen. 
Wenn ich die Themen getrennt betrachte, kann man besser was aufbauen, ist dann aber auch deutlich künstlicher/ praxis fern.

**Comment by AMatutat** [comment]
> wie schreibe ich die try/catch: besser einzelne try/catch um jede anweisung vs. die logik in einem try/catch ...

Idee: Code vorgeben, alles in einen try block und `catch (Excetpion e)`. Die Aufgabe wäre es, den Code so umzubauen, dass sinnvolle try catch blöcke entstehen.

> werfe ich eine checked oder unchecked?

Idee: Verscheidene eigene Exceptions + Anwendungsbeschreibung vorgeben. Diskussion ob diese besser checked oder unchecked sein sollte. 

> wie geht finally und try-with-resources

Eigene Klasse soll so erweitert werden, dass sie als Ressource behandelt werden kann. Der vorgegebene Try-Catch-Finally Block soll erklärt und dann in einen try-with-ressources Block umgeschrieben werden,

**Comment by cagix** [comment]
klingt doch nach nem plan.
