### ISSUE TITLE
Mid-Semester Stimmungsumfrage

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#464]
Für das Projekt müssen wir eine Zwischenevaluation durchführen (Semester Ilias Umfrage). 
Können hier auch Fragen sammeln.

**Comment by AMatutat** [comment]
@alle

Bitte mögliche Fragen für eine Umfrage hier Sammeln um Feedback von den Studis einzuholen.

**Comment by AMatutat** [comment]
Wie sehr stimmen Sie der Aussage zu (Praktikum):

1. Das Praktikum hat mir spaß gemacht
3. Der Umfang der Praktikumsaufgaben war zu gering.
4. Der Umfang der Praktikumsaufgaben war zu groß.
5. Die Konzeptaufgaben haben mir beim Verständniss der Inhalte geholfen.
6. Die Konzeptaufagaben waren zu einfach.
7. Die Konzeptaufgaben waren zu schwer.
8. Die Konzeptaufgaben waren für mich überflüssig.
9. Ich kam gut mit der freien Auswahl der Dungeonaufgaben zurecht.
10. Das erstellen des Dungeon hat mir spaß gemacht. 
11. Ich habe mich bei der freien Auswahl der Dungeonaufgaben schwer getan. 
12. Ich fande es gut, dass die Dungeonaufgaben viel interpretations Spielraum gelassen haben.
13. Das vorgegeben Framework fande ich hilfreich.
14. Das vorgegebene Framework war zu komplex.
15. Das vorgegebene Framework hat mich bei der Umsetzung oft eingeschränkt/behindert.
16. Die Freien Dungeonaufgaben (selber etwas Ausdenken) haben mir gut gefallen.

Wie sehr stimmen Sie der Aussage zu (Vorlesung/Allgemein):

1. Die Zeit, die ich für PM aufgebracht habe, war zu viel.  
2. Die Zeit, die ich für PM aufgebracht habe, war zu wenig.  
3. Die Videoaufzeichnungen gefallen mir besser als klassische Vorlesungen.
4. Die Videoaufzeichnungen gefallen mir genauso wie klassische Vorlesungen.
5. Die Videoaufzeichnungen gefallen mir weniger als klassische Vorlesungen.
6. Mit der Bereitstellung der Inhalte per Webseite kam ich gut klar.
7. Ich hätte mir gewünscht, die Vorlesungsthemen in beliebiger Reihenfolge abarbeiten zu können. 


"Freitext"

Wie viel Zeit haben Sie im durschnitt pro Woche für
- Vorlesung
- Konzeptaufgabe
- Dungeonaufgabe 

im selbststudium verbracht.

**Comment by cagix** [comment]
finde ich gut. ich habe ein paar typos korrigiert und eine frage zur vorlesung hinzugefügt.

beim praktikum sollten wir das in drei kategorien sortieren: (a) allgemein, (b) konzeptaufgaben und (c) dungeonaufgaben

**Comment by cagix** [comment]
@AMatutat Bitte schaue mal in den PM-ILIAS. Dort habe ich die Umfrage aus dem letzten Jahr reinkopiert. Da stehen viele Fragen bereits drin :) ... Das müssten wir entsprechend anpassen/ergänzen/aufräumen (manche Dinge gelten so nicht mehr).

**Comment by CrappyAlgorithm** [comment]
Eine Freitextfrage, zu was war zu schwer/einfach oder unverständlich/schwer zu verstehen, könnte auch interessant sein.

**Comment by jedi101** [comment]
Die oben aufgeführten Fragen finde ich auch, damit sollte sich ein breit gefächertes feedback einholden lassen.

Die Frage:
> Die Durchführung der Vorlesung als Flipped Classroom ist für mich bereichernd.

Würde ich vielleicht in:

"Die Durchführung der Vorlesung als Flipped Classroom hat mir gefallen:" (auf einer Skala von 0 (gar nicht) bis 10 (sehr gut)

**Comment by cagix** [comment]
hab ich mal angepasst

**Comment by AMatutat** [comment]
@cagix 

Ich hab die Liste https://github.com/PM-Dungeon/PM-Lecture/issues/464#issuecomment-1139520346 in das Ilias übertragen. Ich habe es mit den alten Fragen abgeglichen/kombiniert und in Matrix-Fragen gepackt. 

Du müsstest nochmal schauen, ob die Frage zur Parcour-Prüfung bearbeitet werden muss. Ich komm mit den ganzen Formen immer durcheinander.

**Comment by cagix** [comment]
mange takk. schaue ich mir morgen an und schalte das dann frei und mache hier zu.

**Comment by cagix** [comment]
wow

**Comment by AMatutat** [comment]
@cagix magst du das weiter ausführen?

**Comment by cagix** [comment]
nö 🤣

**Comment by AMatutat** [comment]
Wow

**Comment by cagix** [comment]
hihi :)

**Comment by cagix** [comment]
@AMatutat Alles gut. Ich hänge immer noch am E1 - absolut phänomenal :/ ... Wir hätten die Umfrage vorher machen sollen, ich ahne nix Gutes.

**Comment by cagix** [comment]
@AMatutat Sah gut aus. Ich hab noch ein paar Typos korrigiert, bei der Vorlesung die Reihenfolge angepasst (da muss man echt aufpassen, dass man auf die hoch/runter Pfeile und nicht versehentlich 1 Pixel daneben und auf "-" klickt) und den Text für die Parcoursprüfung korrigiert. 

Ist jetzt online, und die Mail/Timeline ist auch raus. 

Danke Dir für die Vorarbeit :)

**Comment by cagix** [comment]
> @AMatutat Sah gut aus. Ich hab noch ein paar Typos korrigiert, bei der Vorlesung die Reihenfolge der Teilfragen angepasst (da muss man echt aufpassen, dass man auf die hoch/runter Pfeile und nicht versehentlich 1 Pixel daneben und auf "-" klickt) und den Text für die Parcoursprüfung korrigiert.
> 
> Ist jetzt online, und die Mail/Timeline ist auch raus.
> 
> Danke Dir für die Vorarbeit :)
