### ISSUE TITLE
Zuordnung alter Praktikums/Übungsaufgaben zu den Themen der Vorlesungen

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#47]
Wir haben einen ziemlich großen Pool an alten Aufgaben, dieser sollte begutachtet werden und die einzelnen Aufgaben zu den entsprechenden Vorlesungsthemen zugeordnet werden.

**Comment by cagix** [comment]
@AMatutat Ist das Ticket eigentlich gelöst? Sonst bringt #182 auch nicht sooo viel, oder?

**Comment by AMatutat** [comment]
im großen ganzen denke ich schon. Es gibt bestimmt noch Aufgaben die wir jetzt nicht recycelt haben, aber ich bin zufrieden.
#182 sollte davon aber so oder so ausgenommen sein. Wir bauen die Aufgaben zu den Vorlesungen, nicht die Vorlesungen zu den Aufgaben.
