### ISSUE TITLE
[QUESTION] PM-Dungeon Praktikum Ablauf

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#48]
Die Aufgabenblätter für die Aufgaben IM Dungeon müssen überarbeitet/erstellt werden. 
Dafür sollten wir uns auf einen Ablauf einigen. 

Idee 1 Klassisch:
- regelmäßige Arbeitsblätter mit fester Struktur (Blatt 1 -> Blatt 2-> ... -> letztes Blatt"
- pro: 
   - bekannt
   - klare Struktur
   - klarer Zusammenhang zwischen dem Thema der Vorlesung und dem Praktikum (jeweils aus der gleichen Woche)
   - einfacher für die Tutoren
- con:
   - sehr statisch
   - keine Flexibilität welche Technik für welches Problem genutzt wird, 

Idee 2 Aufgabenpool:
- die Aufgaben werden als ein großer Pool zur Verfügung gestellt und die Studis können die Aufgaben in jeder beliebigen Reihenfolge abarbeiten
- pro: 
   - Die Studis müssen selbst auf die Idee kommen, welche Technik für welche Aufgabe am besten geeignet ist 
   - Flexibilität für die Studis
   - Abwechslungsreichere Lösungen
 - con:
    - größere Korrekturanforderung an die Tutoren
    - keine Technik als Vorgabe. Was ist, wenn jemand alle Aufgaben auf die "dümmste" Weise umsetzt? 
    - Wie viele Aufgaben pro Woche? Manche Features sind komplexer/aufwendiger als andere. 
       - könnte man da mit einem Werte-System arbeiten? Jede Aufgabe bekommt, abhängig vom Aufwand, einen Wert und jede Woche müssen Aufgaben gemacht werden, die zusammen einen Wert x haben. 

Andere Fragen:
- wollen wir das Projekt am Ende des Semesters beibehalten? 
- Lerntagebuch?
- In Sysprog haben wir über "Konzept-Abnahmen" gesprochen. Können/wollen wir das auch integrieren? Wird das evtl. zu viel? Dann hätten wir Trockenübung, Konzept und Dungeon.

**Comment by cagix** [comment]
ich finde die idee eines aufgabenpools sehr charmant. man kann die struktur jeweils analog zu den blättern gestalten, d.h. die leute haben immer eine feste struktur.

und man könnte eine zuordnung zu den vl-inhalten vornehmen. 

man könnte auch einen "bearbeitungspfad" vorschlagen oder aufgaben zu wochen zuordnen. letzteres entspricht dann eher wieder den bisherigen blättern.

man müsste mindestanforderungen an die bearbeitung formulieren, damit die studis es sich nicht zu einfach machen.

durch die unterscheidung in konzeptaufgaben und dungeonaufgaben können wir die inhalte und die tiefe besser steuern. im dungeon wird es eher freier und kreativer zugehen, für die konzeptaufgaben wird es eher feste vorgaben und units geben.

**Comment by cagix** [comment]
@AMatutat schau doch mal bitte ins wiki, manche deiner fragen hatten wir doch längst diskutiert. 

ja, das lerntagebuch soll es weiterhin geben. man könnte mal drüber nachdenken, ob es einzelne tagebücher werden sollen oder ein fortlaufendes, also eine art blog.

und ja, ein projekt gegen ende sollte es auch geben, wenn ich mich richtig erinnere. vorher sind auch die aufgaben im dungeon schon recht gut vorgegeben, im mini-projekt sollen sie sich austoben.

**Comment by cagix** [comment]
ähnlich, trockenübung == konzeptaufgaben. das waren nur unterschiedliche namen, weil wir das mopped noch nicht richtig fassen konnten. aber ein catchy name wäre schon hilfreich :)

**Comment by AMatutat** [comment]
> @AMatutat schau doch mal bitte ins wiki, manche deiner fragen hatten wir doch längst diskutiert.

Für unsere Diskussionen Typisch haben wir aber noch nicht richtig den "SO!" Punkt festgelegt. Evtl. hätte ich meine Fragen auch genauer stellen sollen.

> ja, das lerntagebuch soll es weiterhin geben. man könnte mal drüber nachdenken, ob es einzelne tagebücher werden sollen oder ein fortlaufendes, also eine art blog.

Ich mag die Blog Idee. Stellen wir dafür "Infrastruktur" bereit (ich denke da an GitHub-Pages)? 

> ähm, trockenübung == konzeptaufgaben

Ne das meinte ich nicht. Wir (ich glaube eigentlich BC) hatten in Sysprog die Idee, das die Studis ihre Modellierung aus dem Lerntagebuch Vorstellen BEVOR sie dann in die Implementierung gehen. 

Und ja, wir brauchen mal einen guten/offiziellen Namen dafür.



Für die Aufgaben-Pool Geschichte bereite ich mal "Dummys" für Freitag vor. Dann haben wir evtl. ne bessere Vorstellung wie das aussehen könnte.

**Comment by cagix** [comment]
> > @AMatutat schau doch mal bitte ins wiki, manche deiner fragen hatten wir doch längst diskutiert.
> 
> Für unsere Diskussionen Typisch haben wir aber noch nicht richtig den "SO!" Punkt festgelegt. Evtl. hätte ich meine Fragen auch genauer stellen sollen.

ja, wir haben noch nirgendwo wirklich entscheidungen getroffen, aber wir hatten im wiki die richtung schon recht gut eingegrenzt


> 
> > ja, das lerntagebuch soll es weiterhin geben. man könnte mal drüber nachdenken, ob es einzelne tagebücher werden sollen oder ein fortlaufendes, also eine art blog.
> 
> Ich mag die Blog Idee. Stellen wir dafür "Infrastruktur" bereit (ich denke da an GitHub-Pages)?

gute frage. gh-pages werfen wieder die frage nach impressum und so auf. aber man könnte das wiki in den projekten nutzen oder eine markdown-datei einchecken+pflegen, die ja dann auch gerendert wird. alternativ könnte man auch über ein blog im ilias nachdenken, aber dann haben wir wieder mehrere punkte, wo informationen verstreut sein können (ilias, gh, ...). ich fände es besser, wenn wir im ilias nur den verweis auf gh/gl haben und sonst nur die organisation machen. naja, und punkte sammeln o.ä. ... 


> 
> > ähm, trockenübung == konzeptaufgaben
> 
> Ne das meinte ich nicht. Wir (ich glaube eigentlich BC) hatten in Sysprog die Idee, das die Studis ihre Modellierung aus dem Lerntagebuch Vorstellen BEVOR sie dann in die Implementierung gehen.

ja, verstehe. das ist natürlich auch noch eine dritte variante. 

vielleicht: 

- konzeptübung, abgabe vor sprechstunde, autograding, diskussion in sprechstunde
- trockenübung: studis geben vor der sprechstunde ihr konzept im lerntagebuch ab, das wird von den tutoren kurz bewertet plus feedback 
- praktikum: vorstellung der dungeon-aufgaben


> 
> Und ja, wir brauchen mal einen guten/offiziellen Namen dafür.

definitiv. und zwar möglichst "nett" und einprägsam.


> 
> Für die Aufgaben-Pool Geschichte bereite ich mal "Dummys" für Freitag vor. Dann haben wir evtl. ne bessere Vorstellung wie das aussehen könnte.

👍

**Comment by AMatutat** [comment]
Um unser Meeting von letzter Woche nachzutragen: 

### Aufgaben
Die verschiedenen Dungeon Aufgaben werden verschiedenen Pools zugeordnet ("A","B","C"). Aus jedem Pool müssen die Studierenden 50%(?) der Punkte holen um das Praktikum zu bestehen (ähnlich wie ein Testat). Die Note ergibt sich aus der Gesamtpunktzahl. Die Studierenden können die Reihenfolge der Aufgaben selbst bestimmen. Die Aufgaben geben verschieden viele Punkte.
Sollte eine Aufgabe nicht mit voller Punktzahl bewerten worden sein, kann sie in der nächsten Woche nochmal (verbessert) Abgegeben werden. Dafür wird im Repo der Studis eine Datei mit Kritikpunkten angelegt. 

Um konstantes Arbeiten zu fordern, können jede Woche maximal 15-Punkte geholt werden. Um volle Punktzahl (100%) zu erreichen, reicht es aber nur 10-Punkte pro Woche zu holen.  
Ein Pool enthält zwei Projekte für jeweils 20 Punkte (diese sind von der 15-Punkte Regel ausgenommen). Projekte werden über zwei Wochen bearbeitet. 

Nachdem die Themen in der Vorlesung behandelt wurden wird Code-Stile, Logging, JUnit und Javadoc als Voraussetzung betrachtet und ggf. mit Punktabzug durchgesetzt. 

Jede Woche gibt es Konzeptaufgaben. Diese gehören zu einen eigenen Pool "Konzept"., daher müssen auch mindestens 50% der Konzeptpunkte geholt werden um das Praktikum zu bestehen. Anders als Dungeonaufgaben gibt es für Konzeptaufgaben klare Abgabedaten. Die Punkte der Konzeptaufgaben zählen nicht zur 15-Punkte Regel. 

Die Konzeptaufgaben werden mithilfe der Toolchain kontrolliert. 

### Workflow der Studis:
Für die Konzeptaufgaben wird jeder Studierendengruppe ein privates Repository gegeben, welches die Vorgaben enthält.
In diesem Repo lösen die Studierenden die Aufgaben. Sie haben keine schreibrechte auf dem master.
Ihre Aufgaben geben sie  dann als PR in den Master ab. Alle Änderungen nach der Deadline werden nicht berücksichtig.
Die Tutoren laufen dann am ende nochmal über die Repos und Sammeln die Ergebnisse ein. 
Zu jeder Konzeptaufgabe gehört ein Projekttagebuch. Die genaue Form müssen wir noch diskutieren. 

Für das Dungeon forken die Studis sich das desktop-repo. Die Dungeonaufgben werden wie üblich im Praktikum vorgestellt. 


### Anhang 
Die Excel Tabelle zum Überblick:
[PoolPM.xlsx](https://github.com/PM-Dungeon/PM-Lecture/files/8063724/PoolPM.xlsx)



@cagix Bitte einmal auf Klarheit prüfen, dann würde ich das im Wiki eintragen.

**Comment by cagix** [comment]
es fehlt noch, dass es x wochen gibt, aber nur (x-1)*10 die 100% sind, also eine woche ausgelassen werden kann.

**Comment by AMatutat** [comment]
https://github.com/PM-Dungeon/PM-Lecture/wiki/Konzept
