### ISSUE TITLE
[QUESTION] Change Repo-Name?

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#50]
Wir haben unsere Organisation "PM-Dungeon" und das Vorlesungs-Repo "Lecture" genannt. Das passt auch eigentlich ganz gut.

Aber mir ist kürzlich aufgefallen, wenn Studis sich das Repo forken, dass dann der Fork im Studi-Repo auch einfach nur "Lecture" heisst, was nicht besonders aussagekräftig ist.

Mein Vorschlag ist, dass wir den Namen für das Lecture-Repo nochmal überdenken. Vielleicht "PM-Lecture" (bestes denglisch)?

@AMatutat @Tobias321 Was denkt Ihr?

**Comment by Tobias321** [comment]
Good Thoughts, "PM-Lecture" klingt gut, als Alternative könnte man "PM-Vorlesungsmaterialien" verwenden, aber das klingt schon wieder etwas umständlich...

**Comment by cagix** [comment]
ja, "PM-Vorlesungsmaterialien" ist ein bisschen lang :)  ...

**Comment by AMatutat** [comment]
Großer denglisch fan, also `PM-Lecture` find ich gut. 
Falls sich jemand beschwert: PM=programming methods

**Comment by AMatutat** [comment]
Großer denglisch fan, also `PM-Lecture` find ich gut. 
Falls sich jemand beschwert: PM=programming methods

**Comment by cagix** [comment]
hihi ... Du bist gut 👍

**Comment by AMatutat** [comment]
manche sagen, der Beste

**Comment by cagix** [comment]
hättest mal geschwiegen ;) ...
