### ISSUE TITLE
[Vorgaben] Aufgabe und Vorgaben zu RegExp missverständlich

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#513]
Die Vorgaben zur RegExp-Aufgabe scheinen übereifrig zu sein und beispielsweise innerhalb von Kommentaren auch Keywords und Annotationen etc. zu erkennen. Dies führt zu Verwirrung bei den Studis.

Entweder sollte die Aufgabenstellung angepasst werden, damit das klar wird: "Die RegExp müssen auf eine mögliche Verschachtelung keine Rücksicht nehmen bzw. dies nicht erkennen. Die Vorgabe baut das aber ggf. verschachtelt zusammen."

Alternativ sollte die Vorgabe keine Verschachtelungen erkennen, sondern einfach nur die RegExps, so wie sie von den Studis kommen.

Edit: Ich fände die zweite Variante besser, da es zu weniger Überraschungen kommt.

**Comment by TGrothe** [comment]
@cagix Die Abgabe von Blatt 08 ist bis heute, 18 Uhr. Ich schlage vor, wir ergänzen kurzfristig nur die Aufgabenstellung. => Sie müssen sich um die Einfüge-Reihenfolge Ihrer RegExp keine Gedanken machen.

Ich denke, alles andere würde mehr kaputt machen als fixen...

**Comment by cagix** [comment]
> @cagix Die Abgabe von Blatt 08 ist bis heute, 18 Uhr. Ich schlage vor, wir ergänzen kurzfristig nur die Aufgabenstellung. => Sie müssen sich um die Einfüge-Reihenfolge Ihrer RegExp keine Gedanken machen.
> 
> Ich denke, alles andere würde mehr kaputt machen als fixen...

Hmmm, haste wahr. Da macht es auch keinen Sinn (mehr), an der Aufgabe noch rumzuprökeln. Das erreicht ja niemanden mehr.

Ein paar Leute haben mich verwirrt nachgefragt, dass ja die RegExps keine Verschachtelung erkennen sollen/müssen, dies aber irgendwie trotzdem passiert (durch die Vorgabe). Deshalb dieses Ticket - die Sache muss für den nächsten Lauf gradegezogen werden.

**Comment by TGrothe** [comment]
Bitte den PR #516 zunächst nicht beachten.
***

Aber das sollte sich einfach beheben lassen:

```java
        // Sort the list so that other surrounding elements are placed in front.
        for (int i = 0; i < tokens.size(); i++) {
            for (int j = i + 1; j < tokens.size(); j++) {
                if (!isSurrounded(tokens.get(i), tokens.get(j))) {
                    Collections.swap(tokens, i, j);
                }
            }
        }
```

Wir kehren hier das Sortierkriterium einfach um:

```java
                if (isSurrounded(tokens.get(i), tokens.get(j))) {
                    Collections.swap(tokens, i, j);
                }
```

Dann sollte alles richtig dargestellt werden, d. h. keine Kommentare innerhalb von Kommentaren o. ä.

Aber das ist dann eine Anpassung fürs nächste Jahr.

**Comment by TGrothe** [comment]
@cagix Jap, das einfache Invertieren der Bedingung (! entfernen) reicht schon aus. 🙂 :

![1_vorher](https://user-images.githubusercontent.com/85501570/172453383-61ab9410-813b-4153-ae6b-dc6629b37327.png)

![2_nachher](https://user-images.githubusercontent.com/85501570/172453426-39869819-4c84-43f9-a3b2-8b88c9faedcf.png)

Sollte ich dann einen neuen PR stellen im homeworks? ... Oder würde das jetzt wahrscheinlich alles durcheinanderbringen?

**Comment by cagix** [comment]
> Sollte ich dann einen neuen PR stellen im homeworks? ... Oder würde das jetzt wahrscheinlich alles durcheinanderbringen? 

in homework kannst du das eigentlich einkippen. das schauen sich die tutoren ja nur als ideen-geber an, und ich denke, dass sie hier vor allem auf die regexps schauen und die vorgaben gar nicht ausführen.

aber das vorgabe- und semester-repo sollten wir nicht aktualisieren. das führt nur zu verwirrungen. und nächstes semester gibts die ja dann voraussichtlich neu :)
