### ISSUE TITLE
Name für die "Konzeptübungen" gesucht

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#53]
Bitte schöne Namen für die Konzeptübungen sammeln.

**Comment by Tobias321** [comment]
- Dungeon-Skills
- Dungeon-Knowledge
- Dungeon-Drill

😉

**Comment by cagix** [comment]
Drill hat was 😎🤣

**Comment by Tobias321** [comment]
Ok, wenn es nicht zu "ordinär" klingt, dann bin ich auch für "Dungeon-Drill" 👍🏻 😉

**Comment by cagix** [comment]
> Ok, wenn es nicht zu "ordinär" klingt, dann bin ich auch für "Dungeon-Drill" 👍🏻 😉

hmmm, ja, nein. das können wir nicht bringen. 

ich habe mal bei anderen geschaut, dort heisst das einfach "quiz" oder "selbsttest". vielleicht sollten wir das auch in die richtung verstehen, obwohl wir eigentlich noch die ilias-quizzes machen wollen. hmmm.

**Comment by AMatutat** [comment]
"Quiz" ist doof, weil schon belegt.
Und wenn wir es klassisch "Übung" nennen? Könnte aber zu Verwirrungen kommen, da die meisten Übungen in der FH freiwillig sind. 
"Selbsttest" klingt mir auch viel zu sehr nach optional.

**Comment by cagix** [comment]
aye ... das ist ja der ganze ärger dabei. dann doch "drill" ;) ...

neee, lasst mal den brain bush weiter schütteln, vielleicht fällt ja noch was raus.

**Comment by CrappyAlgorithm** [comment]
Bei Drill habe ich direkt ein Logo vor Augen. So ein Studi vor nem Pc und Carsten/Andre dahinter mit Peitsche. ;-)

Wie waere etwas mit basic im Namen?
So z.B. Dev-Basics oder Basic-Skills

**Comment by AMatutat** [comment]
> Dev-Basics

Das find ich irgendwie nett

**Comment by CrappyAlgorithm** [comment]
PM-Basics-Challenges, oder kurz PM-Challenges faende ich auch nett, vielleicht koennte das den ein oder anderen sogar motivieren. Weil das ist dann ja eine Challenge und kein Test/Uebung mehr. ^^

**Comment by cagix** [comment]
Dev-Basics hat einen netten Ton (zu nett?). PM-Challenges finde ich aber auch gut. 

Oder vielleicht einfach nur "Challenges"? Das macht dann auch den Charakter deutlicher -- es ist eben eine Challenge, man muss sich ein wenig anstrengen?

**Comment by cagix** [comment]
> Bei Drill habe ich direkt ein Logo vor Augen. So ein Studi vor nem Pc und Carsten/Andre dahinter mit Peitsche. ;-)

genau so soll es auch sein ;)

**Comment by Tobias321** [comment]
Ok, hier meine Rangliste:

Name | Rank
-- | --
PM-Challenges | 🌟 🌟 🌟
Dev-Basics | 🌟 🌟
Dungeon-Drill | 🌟


;)

**Comment by cagix** [comment]
@AMatutat Vielleicht brauchen wir aber auch keinen Namen. Wir haben ja die Pools "A", "B" und "C". Und dann tun wir die Konzept-Aufgaben nach Pool "C" und geben denen ein Abgabedatum, während bei "A" und "B" die Studis selbst planen sollen? Wäre das ein Weg?

**Comment by AMatutat** [comment]
Hab erstmal einen Pool "K" angelegt. Aber ja, reicht hals auch als Name.

**Comment by cagix** [comment]
Macht Sinn. Mehr als vier Pools sollten wir aber nicht machen: Konzept, Dungeon easy, Dungeon harder, Projekt. Was war Deine Idee, also wonach wolltest Du die Aufgaben unterteilen?

**Comment by AMatutat** [comment]
Aktuelle hab ich fünf Pools. Dungeon A,B,C, Projekt und Konzept. 
A: Anfang, Held und eher technische Aufgaben (z.B Speichern und Laden)
B: Monster und Kampf Aufgaben
C: Items, UI, other
K: Konzeptaufgaben
P: Projekt

**Comment by cagix** [comment]
hmmm, fünf pools sind gefühlt zwei zuviel. naja, müssen wir im auge behalten.

konzept und projekt zu trennen finde ich sinnvoll. aber müssen wir (a) und (b) und (c) unterscheiden bzw. erzwingen, dass hier bestimmte aufgaben gemacht werden? reichen da evtl. zwei kategorien?

**Comment by AMatutat** [comment]
Ich muss mal ein wenig mit der Verteilung rumspielen und gucken ob da was sinniges bei rauskommen kann.
Mit mehreren Pools kannst man halt ein wenig mehr Erzwingen. Wenn alle Kampf und alle Inventar Sachen in einem Pool liegen, dann gibt es evtl. Teams die nur Kampfkram und andere Teams die nur Inventarkram machen. Mit der aktuellen Aufteilung muss zumindest jeder ein wenig Kampf und ein wenig Inventar machen und kann sich dann auf die Ausarbeitung eines der Bereiche fokussieren.

**Comment by cagix** [comment]
> Ich muss mal ein wenig mit der Verteilung rumspielen und gucken ob da was sinniges bei rauskommen kann.
> 
> Mit mehreren Pools kannst man halt ein wenig mehr Erzwingen. Wenn alle Kampf und alle Inventar Sachen in einem Pool liegen, dann gibt es evtl. Teams die nur Kampfkram und andere Teams die nur Inventarkram machen. Mit der aktuellen Aufteilung muss zumindest jeder ein wenig Kampf und ein wenig Inventar machen und kann sich dann auf die Ausarbeitung eines der Bereiche fokussieren. 

stimme ich voll zu. andererseits macht es das system für die studis wieder komplizierter und fehleranfälliger. und die frage ist, ob es fachlich gesehen nun einen so großen unterschied machen würde, ob nun jemand mehr kampf oder mehr inventar macht.

**Comment by CrappyAlgorithm** [comment]
> Ich muss mal ein wenig mit der Verteilung rumspielen und gucken ob da was sinniges bei rauskommen kann. Mit mehreren Pools kannst man halt ein wenig mehr Erzwingen. Wenn alle Kampf und alle Inventar Sachen in einem Pool liegen, dann gibt es evtl. Teams die nur Kampfkram und andere Teams die nur Inventarkram machen. Mit der aktuellen Aufteilung muss zumindest jeder ein wenig Kampf und ein wenig Inventar machen und kann sich dann auf die Ausarbeitung eines der Bereiche fokussieren.

Könnte man nicht einzelne Aufgaben aus dem zusammengelegten Pool ABC als verpflichtend flaggen, um das zu umgehen? Oder das als seperater Pool in Form von Mindestanforderungen? Da würde ich so Sachen, wie Laden/Speichern, simpler Nahkampf, simple Monster, etc. sehen.

**Comment by cagix** [comment]
flaggen wollten wir vermeiden, weil das eine zusätzliche ebene reinbringt ..."machen die mind. x aufgaben aus diesem pool, und dabei alle markierten". 

andererseits sind viele pools eben auch unübersichtlich.

**Comment by AMatutat** [comment]
@cagix hat sich eigentlich gegessen, oder?

**Comment by cagix** [comment]
jupp.
