### ISSUE TITLE
[VL] End-Semesterumfrage

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#551]
Wir sollten bis nächste Woche (27.6.) die End-Umfrage erstellen. Ich habe die Zwischenumfrage im ILIAS bereits kopiert.

TODO:

- [x] Fragen rauswerfen? (Brauchen wir wirklich alle Fragen nochmal?)
- [x] Skala bei den Zeit-Fragen anpassen
- [ ] Fragen spezifisch zu Selbstgesteuertem Lernen, Dungeon etc. stellen

**Comment by AMatutat** [comment]
Ich glaube gezielte Fragen für das E-Assesment wären auch sinnig. 
Einmal ob die Zeit gereicht hat oder nicht aber vor allem ob die Erwartungen an die Prüfung anders waren. Also andere Fragen Typen etc.

**Comment by AMatutat** [comment]
> Fragen rauswerfen? (Brauchen wir wirklich alle Fragen nochmal?)

Denke die ganzen "Fanden Sie sich zu recht", " kamen sie damit klar", Lerntagebuch Fragen können raus. Da wird sich nichts geändert haben.

**Comment by AMatutat** [comment]
@cagix Ich hab die m.M.n unnötigen Fragen rausgeworfen und nur die behalten, wo neue Eindrücke neue Ergebnisse liefern könnten.
Zeiten für Konzept und Dungeon hab ich auch erweitert.
Dann hab ich noch ein paar Fragen zum E-Assessment und zum Praktikum hinzugefügt. Ein paar der Matrixfragen hab ich angepasst/erweitert.

**Comment by cagix** [comment]
Alles klar, danke! Dann schaue ich mir das nachher gleich mal an und schalte es online. 

Danke Dir :)

**Comment by cagix** [comment]
@AMatutat So, dat Dingens ist online. Danke für die Vorbereitung!

**Comment by AMatutat** [comment]
Bin mal gespannt was da rum kommt.

**Comment by cagix** [comment]
jo. hab noch ein paar typos korrigiert ("internat" => "internet" und so), aber sonst war das schon recht viel. und ich bin ziemlich sicher, was bei der frage nach der zeit im e-assessment rauskommt :)
