### ISSUE TITLE
Orga: Lessons learned

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#569]
Wir sollten wieder ein Lessons-Learned machen (PM-Dungoen-Team, Tutoren, Jonas, BC => vgl. Mail vom 01.07.22 14:41 "PM: Bitte Punkte im ILIAS eintragen und einen schönen Sommer ..."). 

@AMatutat Kannst Du bitte einen Termin (90') für nächste Woche (KW28) organisieren? Wir könnten den alten Termin der Tutoren-Runde nehmen (Di, 18:00 Uhr). Da aber grad Prüfungen sind, würde ich Montag (14:00 Uhr, 18:00 Uhr), Mittwoch (10:00 Uhr, 18:00 Uhr) und Donnerstag (10:00 Uhr, 14:00 Uhr, 18:00 Uhr) je einen Ersatztermin vorschlagen => https://terminplaner4.dfn.de

**Comment by AMatutat** [comment]
Terminanfrage ist versendet

**Comment by cagix** [comment]
@AMatutat Gibts nen Termin?

**Comment by AMatutat** [comment]
Termin ist Mittwoch, den 13. Juli 2022 - 18 Uhr, Mail ist raus
