### ISSUE TITLE
Neues Thema: Spring Boot?

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/PM-Lecture#59]
Spring Boot ist ja ein recht populäres Framework im Java-Bereich. 

- Macht es Sinn, das in eine Lehrveranstaltung mit Java-Fokus zu integrieren?
- Ist es evtl. zu komplex für ein zweites Semester?
- Ist es evtl. zu komplex für 1..2 Blöcke a 15..20 Minuten?
- Wird es im Studium schon an anderer Stelle besprochen?

**Comment by cagix** [comment]
@AMatutat Mach mal ein Grundkonzept für die VL, den Rest mache ich dann weiter :)

**Comment by AMatutat** [comment]
Na wenns sonst nix ist. ^^

**Comment by cagix** [comment]
Besprechung 01.03.2022: Spring lassen wir raus. Das Framework ist zu groß, als dass man es in den 20..30 Minuten sinnvoll behandeln kann. Außerdem ist die Kompatibilität zu libGDX fraglich.

Als Ersatz wird JDBC (#190) alleine besprochen und zusätzlich noch der Umgang mit Frameworks allgemein (#191).

Closed.
