### ISSUE TITLE
[FEATURE] Aufgaben erstellen 

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#62]
Die verschiedenen Aufgaben müssen formuliert werden. 

- [x] #63
- [x] #64
- [x] #65
- [x] #66
- [x] #320
- [ ] #89
- [ ] #90

**Comment by Tobias321** [comment]
![Screenshot_20220215-131829.png](https://user-images.githubusercontent.com/85501570/154061141-3d9e0f72-4a02-4b1e-a2ef-48fd6757f86b.png)

Mein Handy randaliert gerade^^

**Comment by AMatutat** [comment]
Sorry... :D

**Comment by Tobias321** [comment]
> Sorry... :D 

Kein Ding, ich hätte ja auch die Benachrichtigungen abbestellen können... :)

**Comment by cagix** [comment]
@AMatutat Was dagegen, wenn ich dieses Meta-Ticket schließe? Die Issues sind ja alle da, und ich sehe grad nicht so richtig den Sinn, die hier nochmal zu tracken? Dann ist wieder ein Ticket mehr zu ;)
