### ISSUE TITLE
Aufgaben Pool A

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#63]
Die Aufgaben aus dem Pool A müssen erstellt werden

- [x] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [ ] #71

**Comment by cagix** [comment]
@AMatutat Gib mir mal bitte ein oder zwei Worte, welche die Aufgaben in dieser Gruppe gut umschreiben. Trifft es "Basics" richtig? Mir sieht es danach aus, als ob die obigen Aufgaben ein rudimentäres Spiel ermöglichen.

**Comment by cagix** [comment]
@AMatutat Was dagegen, wenn ich dieses Meta-Ticket schließe? Die Issues sind ja alle da, und ich sehe grad nicht so richtig den Sinn, die hier nochmal zu tracken? Dann ist wieder ein Ticket mehr zu ;)
