### ISSUE TITLE
Aufgaben Pool C

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#65]
Die Aufgaben für Pool C müssen erstellt werden

- [ ] #80
- [ ] #81
- [ ] #82
- [ ] #83
- [ ] #84
- [ ] #85
- [ ] #86
- [ ] #87
- [ ] #88

**Comment by cagix** [comment]
@AMatutat Gib mir mal bitte ein oder zwei Worte, welche die Aufgaben in dieser Gruppe gut umschreiben. Trifft es "Items, Aufbewahrung und Handel" richtig?

**Comment by cagix** [comment]
@AMatutat Was dagegen, wenn ich dieses Meta-Ticket schließe? Die Issues sind ja alle da, und ich sehe grad nicht so richtig den Sinn, die hier nochmal zu tracken? Dann ist wieder ein Ticket mehr zu ;)
