### ISSUE TITLE
Konzeptaufgaben

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#66]
Die verschiedenen Konzeptaufgaben müssen erstellt werden 

- [x] #91
- [ ] #92
- [ ] #93
- [ ] #94
- [ ] #95
- [ ] #96
- [ ] #97
- [ ] #98
- [ ] #99
- [ ] #100

**Comment by AMatutat** [comment]
@cagix Ich hab den einzelnen Blättern jetzt die einzelnen Aufgaben zugeordnet. Bitte einmal kontrollieren.

**Comment by cagix** [comment]
> @cagix Ich hab den einzelnen Blättern jetzt die einzelnen Aufgaben zugeordnet. Bitte einmal kontrollieren.

@AMatutat Hmmm? Wo suche ich nach den Zuordnungen? Im Excel (GoogleDocs) oder in den einzelnen Aufgaben?

**Comment by AMatutat** [comment]
Äh ja mein Fehler. In den Issues für die einzelnen Blätter (siehe oben).

**Comment by cagix** [comment]
> Äh ja mein Fehler. In den Issues für die einzelnen Blätter (siehe oben).
> Ich habe die Issues der Aufgaben als Bulletpoint zu den Blätter-Issues gepackt.

verstehe. deshalb hab ich nix gesehen :) ... das ist für mich grad nicht effizient, weil ich jetzt jedes der zehn tickets aufmachen und mit der excel-tabelle vergleichen muss. ich fände es einfacher, wenn du in der excel-tabelle im sheet "wochenüberblick" in spalte u die sheet-nummer und die themen eintragen würdest ...

**Comment by AMatutat** [comment]
[planung_pm_kpool.xlsx](https://github.com/PM-Dungeon/PM-Lecture/files/8197375/planung_pm_kpool.xlsx)

Habs auch im Themen Sheet eingetragen. Sheet-Nummer ist immer identisch mit der P-Nummer und die Aufgaben sind immer in der Woche eingetragen, in der sie vorgestellt werden.

**Comment by cagix** [comment]
> [planung_pm_kpool.xlsx](https://github.com/PM-Dungeon/PM-Lecture/files/8197375/planung_pm_kpool.xlsx)
> 
> Habs auch im Themen Sheet eingetragen. Sheet-Nummer ist immer identisch mit der P-Nummer und die Aufgaben sind immer in der Woche eingetragen, in der sie vorgestellt werden.

hmmm, ich hab das mal in unser google-docs-sheet übertragen und auch die änderung woche8--woche12 mit eingetragen. 

und der "tolle" mechanismus mit der tabelle und der pseudo-pivot-tabelle ist an ein ende der nützlichkeit gekommen, ich habe die beiden sheets mal ausgeblendet und das wochending als werte-kopie angelegt. in zukunft also einfach direkt im wochen-sheet (neu) editieren.

**Comment by cagix** [comment]
aber sonst scheint mir das erstmal zu passen

**Comment by cagix** [comment]
@AMatutat Was dagegen, wenn ich dieses Meta-Ticket schließe? Die Issues sind ja alle da, und ich sehe grad nicht so richtig den Sinn, die hier nochmal zu tracken? Dann ist wieder ein Ticket mehr zu ;)
