### ISSUE TITLE
Aufgabe: Beschreibungstexte für "freie" Aufgaben

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#89]
In alle drei Pools A, B und C gibt es je eine freie Aufgabe mit 10P. 

- [ ] Der Beschreibungstext sollte deutlich machen, dass sich die Studis hier "austoben" dürfen. 
- [ ] Es sollte ein oder zwei Beispiel-Ideen geben, damit die Studis eine Idee des gewünschten Umfangs bekommen.
- [ ] Es sollte deutlich werden, dass hier keine bereits existierenden Aufgaben und auch keine bereits abgegebenen Aufgaben bearbeitet werden können, sondern dass es um neue Ideen geht.

---

Update:

- Für die Projekt-Seite könnte direkt `assignments/pool_p/_index.md` genommen werden, da es darunter nur eine einzige Seite mit der Projektbeschreibung gibt
- Spätestens eine Woche vor Projekt: Im Praktikum Pitch mit Jonas diskutieren
    - Konzept/Pitch kann mdl. sein, dient vor allem der Machbarkeit und Aufwandsabwägung
    - 10P für inhaltliche Dinge absprechen
- Erste Woche: Feinkonzept, Grundgerüst/Grobimplementierung
    - 10 Punkte für Feinkonzept und Grundimplementierung: **TBD**
- Zweite Woche: Implementierung, Dokumentation, Lerntagebuch
    - Inhaltliche Punkte für Umsetzung
    - Punkte für schriftliche Ausarbeitung: **Kriterien TDB**
    - Abzüge wie bei den Dungeon-Aufgaben sonst

=> erstes Projekt: entweder in der Woche vor dem E-Assessment oder in der Woche mit dem E-Assessment

**Comment by cagix** [comment]
@AMatutat Das sind dann die "freien Aufgaben", oder?

**Comment by AMatutat** [comment]
jop.
Lagern wir das irgendwo anders hin aus oder wie ist der plan?

**Comment by AMatutat** [comment]
Lass uns dieses Ticket umwandeln.
