### ISSUE TITLE
Aufgabe: Metadaten

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/PM-Lecture#90]
Die Metadaten für die Aufgaben müssen überprüft und ggf. angepasst werden.
- Stimmen die Punkte?
- Autor?
- ~~ggf. Abgabedatum~~ (wird über `data/schedule.yaml` definiert)
- Gewichtung

**Comment by cagix** [comment]
> Die Metadaten für die Aufgaben müssen überprüft und ggf. angepasst werden.
> 
> * Stimmen die Punkte?

`points: 10`

> * Autor?

`author: "wuppie fluppie"`

> * ggf. Abgabedatum

nein. das kommt nach `data/schedule.yaml`.

> * Gewichtung

`weight: 23`, wobei das die Sortierung im jeweiligen Pool steuert

**Comment by cagix** [comment]
@AMatutat Das Ticket kann zu, oder? Ich hatte vorhin beim Mergen immer ein Auge auf das `weight` gehabt.

**Comment by AMatutat** [comment]
Jop. Ich hatte die Punkte auch nochmal geprüft.

**Comment by cagix** [comment]
@AMatutat Danke für die Unterstützung! Die Webseite ist im ILIAS und live :) Danke!
